### ISSUE TITLE
Bug: Claim commands not working

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#10]
**Minecraft username**: JokerBoss99

* Expected behavior**: Be able to use /claimlist to see how many blocks I have 

**Actual behavior**: Server responds with "/claim has been disabled. Please us a golden shovel to claim instead."

**How can this issue be replicated?:** Do /claimlist, or any claim command that has the word /claim in it

* A screenshot / video link if available**:
![image](https://user-images.githubusercontent.com/49373976/56097957-e92cac80-5ec8-11e9-8151-f0df67f14ce4.png)

**Additional information**: The warning that /claim has been disabled should also be "/claim has been disabled. Please us**e** a golden shovel to claim instead."

**Comment by Kyrobi** [comment]
This issue has been resolved.
