### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Luemasity** [Kyrobi/Cynagen#100]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Luemasity

**I was banned on**: (date) 12/8/2019

**I was banned by**: (Leave blank if unknown) Server

**I was banned for**: Posting inappropriate message on a sign

**A brief summary of what happened before the ban was**: I was typing on a sign

**I like to be unbanned because**: I was unaware of this rule and was only doing it as a joke to my friend. It will not happen again, I learned from my mistake. 

**I often slap little kids because**: I do not

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Just make sure to no do something like that again.

In the meantime, please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: "Hello! I broke Rule #1 Section H"

**Comment by Luemasity** [comment]
Hi! I broke rule #3 section B

**Comment by Kyrobi** [comment]
Just be careful when doing things like that on the server. You are unbanned.
