### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by SkyMan6291** [Kyrobi/Cynagen#101]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Skyman6291

**I was banned on**: (date) Augest 23

**I was banned by**: (Leave blank if unknown)console

**I was banned for**: saying the n word on a sign

**A brief summary of what happened before the ban was**:i wrote the n word on a sign 

**I like to be unbanned because**: i miss the server and all my friends play on it

**I often slap little kids because**: they misbehave 

**Additional information**: (Optional) i have become a born again christian

**Comment by Kyrobi** [comment]
Hello, it seems like this isn't your first offense for using the N-word. 

![image](https://user-images.githubusercontent.com/20980266/72200896-4af85380-3414-11ea-94e1-6c2efbdf6809.png)

In the meantime, please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by SkyMan6291** [comment]
Hello, I believe I have broken rule 3: section a /b I truly feel bad about writing what I did on a sign. To be honest it wasn’t me on my account I had friend over and they asked which server I played on the most and went a head and got me banned after I had already been unbanned. I didn’t intend for any of this to happen

**Comment by Kyrobi** [comment]
You are unbanned. Since this is your 3rd time, you will be mute in-game for 7 days.

**Comment by SkyMan6291** [comment]
Thank you so much ❤️❤️
