### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by jakearator** [Kyrobi/Cynagen#102]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: jakearator

**I was banned on**: (date) 1/10/2020 9:29 PM.

**I was banned by**: (Leave blank if unknown) System. Fuck yo robot dumdum no chin no ass no boobs no chest no face no skin no blood dumdum lookin ass forehead going to china town ass bitch.

**I was banned for**: Typing @everyone.

**A brief summary of what happened before the ban was**: I log on from playing some Halo reach and shitting on kids of course, because im fully gangster in halo reach. I log onto the mIneCrAft server and I say, "I wonder if this still works" and fully enough, it didn't, and I receive a ban. Not epic.

**I like to be unbanned because**: Im a gamer, and I enjoy mInEcRaFt. Minecraft is fun, this server is fun. 

**I often slap little kids because**: I fucking hate little kids, Ifucking hate littl ekids, I fucikng hate littl ekids, I fucking hate little kids, also, I like little kids, not sexual though, don't get it confuised. I like them as a friend, not like the sexual.

**Additional information**: (Optional)
I found by my friend Darien when I was in a call with himwhen I got banned that I was gay. Not epic, no more pussy for your ol' friend jakearator. HMU im lonely, and require healing ahaha get it? Because im genji from the famous video game series Overwatch. Did I ever tell how thiccc (with 3 c's) widowmaker is? like, bitch, sit on my face and call me mommy. Few, give me pink eye while you're at it. Thank you for the meal.
![Mario and lugia](https://user-images.githubusercontent.com/54967605/72197659-d3b1c800-33f1-11ea-9a45-80e818bb0a8f.jpg)
![oh ya baby swag](https://user-images.githubusercontent.com/54967605/72197668-e1674d80-33f1-11ea-9901-ac1015c5560d.jpg)
![Baby yoda](https://user-images.githubusercontent.com/54967605/72197675-ea581f00-33f1-11ea-95d3-606286d5f8df.jpg)

**Comment by Kyrobi** [comment]
Resolved.
