### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by IceKebab** [Kyrobi/Cynagen#103]
Please title this post "Ban Appeal:" followed by a name

**Username**: IceKebab

**I was banned on**: 2020-1-10

**I was banned by**: ColtCrohnie

**I was banned for**: X-ray

**A brief summary of what happened before the ban was**: So I  X-rayed, and after I did that I found  an spider spawner in a biome and decided to make an XP farm.

**I like to be unbanned because**: I got caught and suck at everything and I won't do it again.

**Additional information**: I suck at everything including mining.

**Comment by ColtCrohnie** [comment]
Your ban will be reduced to 7 days however the minerals you gained will be confiscated. A second X-Ray offence will result in a permanent ban with no chance to appeal
