### ISSUE TITLE
Unban Appeal

### ISSUE THREAD

**Issue by rxycz** [Kyrobi/Cynagen#105]
i was banned for typing the 'nword' on a sign on the 13th of July 2019. i was testing  coloured signs and it was the first word to come to mind. I now have a PC and am wanting to play on cynagen again. i am sorry for what i have done & it wont happen again. My username is UTW

**Comment by Kyrobi** [comment]
Please use the correct ban appeal format and try again.

**Comment by rxycz** [comment]
i can’t find the format?...

**Comment by Kyrobi** [comment]
When you open a new issue, you should see see: 

![image](https://user-images.githubusercontent.com/20980266/72674380-354de400-3a3b-11ea-8415-d0c882b8857c.png)

**Comment by rxycz** [comment]
oh yes, first time around i didn’t see it for some reason. thankyou, i’ve
submitted a ban appeal correctly now
