### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by 0x1c1ean** [Kyrobi/Cynagen#107]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (date)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**What's wrong with you?**:

**Additional information**: (Optional)

**Comment by 0x1c1ean** [comment]
oops
my minecraft username is fireboytyler
i was banned on 1/23/2020 from the discord server
i was banned by probably joker
i was banned for being young
i would like to be unbanned because i didnt do anything wrong

**Comment by JokerBoss99** [comment]
Nope, you will not be unbanned from the discord server. 
This is the ban reason I provided when banning you from the discord. "Told user to kill themselves, and their previous actions leads me to believe they haven't, and will not change." 
You were not banned for being young, you were banned for going way too far on multiple occasions. 
You will **not** be unbanned from the discord server, and if your actions and issues translate over onto the Minecraft server, you will find yourself removed from there as well.

**Comment by 0x1c1ean** [comment]
it was clearly sarcasm

**Comment by 0x1c1ean** [comment]
reeeeeeeeeeee

**Comment by JokerBoss99** [comment]
I already told you no, you don't need to bump your thread with "reeeeeeeeeeee", you're just proving my point that you don't need to be on the discord for everyone's sake

**Comment by 0x1c1ean** [comment]
Well then what could i do to disprove uour point and/or get unbanned?

**Comment by JokerBoss99** [comment]
Start behaving better, and we'll think about unbanning you. We will unban you when we feel you're good to. There's no specific date, so don't create any more threads or appeals for it.

**Comment by 0x1c1ean** [comment]
When will i be unbanned again? It's been about a week and a half since

**Comment by JokerBoss99** [comment]
Ah darn I should’ve made it more specific, my last statement applies to comments as well. You’ll be unbanned when we unban you, no need to remind us. Thank you
