### ISSUE TITLE
Ban Appeal: Gay

### ISSUE THREAD

**Issue by Goblinggggg** [Kyrobi/Cynagen#108]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: GoblinGod

**I was banned on**: 1/25/19

**I was banned by**: Server

**I was banned for**: Naming a crossbow faggot fucker, I want to clarify that I am gay and the only person I was going to use it on was an IRL friend of mine who is also gay and cool with me calling them faggot. We were planning to have a bow duel and I thought it would be funny.

**A brief summary of what happened before the ban was**: I put my Crossbow in the anvil with a book and renamed it faggot fucker

**I like to be unbanned because**: I forgot that the name would be broadcasted to the chat if I killed them, which would be bad I agree. If i get unbanned I will change the name so that that doesn't happen. 

**What's wrong with you?**: I'm gay and sad

**Additional information**: :)

**Comment by Kyrobi** [comment]
Careful next time. Your ban will be reduced to 12 hours.

In the meantime, please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md
