### ISSUE TITLE
Ban Appeal: xTyfou

### ISSUE THREAD

**Issue by xTyfou** [Kyrobi/Cynagen#109]
i as banned on the 26/01/2020

I was banned by the console 
i was banned for saying the n-word while writing a joke to my friend on a sign
my friends and i were making jokes to his girlfriend and i made a joke using the nword,
i'd like to be unbanned because i really enjoy this server and the people, i have been playing on here for 2 months with my friends and we have a lot of fun, we say the nword commonly when we talk on discord so i didnt think it through :(

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by xTyfou** [comment]
Hi i broke the Rule #3 Section B

**Comment by Kyrobi** [comment]
You are now unbanned. Please use the correct ban appeal format next time.
