### ISSUE TITLE
Bug: Sprinting w/ speed 2

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#11]
**Minecraft username**: JokerBoss99

* Expected behavior**: Be able to sprint with speed 2 on farmland

**Actual behavior**: Get lagged back consistently

**How can this issue be replicated?**: By sprinting on farmland

* A screenshot / video link if available**: N/A

**Additional information**: It doesn't give an anticheat message for some weird reason (idk if you toggled it off or not for staff)

**Comment by Kyrobi** [comment]
Fixed.
