### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Connx21** [Kyrobi/Cynagen#111]
Ban Appeal

**Connx21**:

**2019-09-02**

**saying the n word**:

**my brother wanted to play on my computer and play mc and said the n word**:

**it me and my friends third year anniversary of playing on the server and i really want to play on it with them**:

**What's your opinion on getting tattoos?**:

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by Kyrobi** [comment]
Failed to respond within 5 days' time, appeal denied.
