### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Debutesche** [Kyrobi/Cynagen#114]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username:** Debutesche

**I was banned on:** ??/??/??

**I was banned by:** a mod probably

**I was banned for:**
I do not know, but probably shit posting

**A brief summary of what happened before the ban was:** I just happened to notice that I was banned from #support

**I like to be unbanned because:** Support is the place for issues and I oft-times have issues

**I often slap kids because:** I hate them, boo, I hate all kids

**Additional information:** This is not a server ban appeal, this is a ban appeal for a channel

**Comment by Kyrobi** [comment]
This is your final warning. If you get banned from Support again, there will be no appeals.
