### ISSUE TITLE
Ban Appeal: Supposedly_Bacon

### ISSUE THREAD

**Issue by SupposedlyBacon** [Kyrobi/Cynagen#115]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Supposedly_Bacon

**I was banned on**: Feb 10, 2020

**I was banned by**: BOT

**I was banned for**: Saying: nibba

**A brief summary of what happened before the ban was**: I had been muted for saying "Nigga" assuming the "a" would bypass any auto flagging stuff. I said it during a chat conversation of users threatening to "say the n-word". I then got a book and quill and was communicating with another user in which I clarified what I had said by typing "nibba" which resulted in the 2-day ban. 

**I like to be unbanned because**: In the first instance of using the ward I was being ironic and in the second explaining why I had been muted

**What's your opinion on getting tattoos?**: I think tattoos are works of art but given the context of the ban I must clarify that hate tattoos (swasticas) are to be frowned upon.

**Additional information**: I will never say the word again ironically or otherwise. I love the community this server hosts. sorry for any inconvenience I have caused

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by SupposedlyBacon** [comment]
Hello! I broke Rule #3 Section B

**Comment by Kyrobi** [comment]
Unbanned.
