### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Superkenthor** [Kyrobi/Cynagen#116]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: BobbyBigBalls

**I was banned on**: Feb 11, 2020)

**I was banned by**: ColtCrohnie

**I was banned for**: X-Ray

**A brief summary of what happened before the ban was**: Was trying to find iron for beacon, got greedy when I saw diamonds, gave diamonds back before I was banned

**I like to be unbanned because**: I wanna be able to play with my friend again

**What's your opinion on getting tattoos?**: I have one. Me and my friends went to a con and I got a "mystery tattoo" which meant that I didn't know what it was until after it was on me. We also filmed the entire thing. (The Video: https://www.youtube.com/watch?v=gca-k557cSE)

**Additional information**:

**Comment by ColtCrohnie** [comment]
If you can show evidence that you don’t have the x-ray client/texture pack anymore I’ll reduce the ban

**Comment by Superkenthor** [comment]
Below I've attached screenshots of my resource pack folder and the two packs I use. My pack only has painting changes (because I made it for a friend initially and I ended up liking them too lol). The second one has the block texture's being shown (not all of them because I don't have the screen size) but you can see most of the important ones (stone, grass, etc). If there's any other way to show evidence that I haven't here just let me know.

![1](https://user-images.githubusercontent.com/5200566/74423929-ef035f00-4e05-11ea-9773-bd95e544bedc.PNG)
![2](https://user-images.githubusercontent.com/5200566/74423936-ef9bf580-4e05-11ea-974e-9bf5a7933e8f.PNG)
![3](https://user-images.githubusercontent.com/5200566/74423937-f0348c00-4e05-11ea-9550-06bbd98ae170.PNG)

**Comment by ColtCrohnie** [comment]
Your ban has been reduced to 3 days, please update yourself of the rules
