### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by StanLeeBigFan** [Kyrobi/Cynagen#118]
Please title this post "Ban Appeal:" followed by a name 

**Minecraft username**:StanLeeBigFan

**I was banned on**: (Feb 17 2020)

**I was banned by**: (Colt)

**I was banned for**:Bullying

**A brief summary of what happened before the ban was**:I was making a joke with my friend bc he had built a wall to keep me out so i built a wall outside his wall i was taking it down then colt showed up and banned me

**I like to be unbanned because**: I truly meant it as a joke and as i said i was taking it down

**What's your opinion on getting tattoos?**:Im 13 and never thought about it

**Additional information**: (I really like cynagen because its the only place i have friends)

**Comment by StanLeeBigFan** [comment]
i dont mean to spam staff but i was taken off discord server so i posted here

**Comment by Kyrobi** [comment]
Unfortunately, you'll have to serve your time.
