### ISSUE TITLE
Ban Appeal: MoonSmurf

### ISSUE THREAD

**Issue by MoonSmurf1** [Kyrobi/Cynagen#120]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: MoonSmurf

**I was banned on**: Feb 21, 2019

**I was banned by**: Console

**I was banned for**: saying the n word.

**A brief summary of what happened before the ban was**: I was explaining a story and one of the people in the story said the n word and I said it in chat because of the story. I was muted for two days for that but was explaining why I was muted on a sign and it banned me.

**I like to be unbanned because**: I love the server. Me and my girlfriend play on it a lot and I would love to be able to come back and fix my mistake and make a new impression.

**What's your opinion on getting tattoos?**: I think it is the persons choice. The only tattoo I am going to get is one of a bulldog with my uncle. The reason for this is because I was in the hospital for a month with severe burns on half my body and want the tattoo to represent getting through the hard time.

**Additional information**: (Optional)
Please let me back in. I am more aware of the rules and regulations of the server now.

**Comment by ColtCrohnie** [comment]
Your ban has been lifted but you’ll be muted in game for 2 more days
