### ISSUE TITLE
Ban Appeal:  Commes

### ISSUE THREAD

**Issue by commes23** [Kyrobi/Cynagen#129]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: commes

**I was banned on**: March 6 2020

**I was banned by**: Auto banned

**I was banned for**: 'racial slur', I said "nibbas".

**A brief summary of what happened before the ban was**: I said "nibbas really be talking to they selves" in chat and I got banned.

**I like to be unbanned because**: Never got a warning and I didn't know "nibbas" was a slur lmfao, seriously though I enjoy the server and would rather not be banned for the weekend.

**Explain why is cereal is/isn't considered a soup**: Bruh, dictionary.com says a soup is hot, who the hell eats cereal hot. 

**Additional information**: I was making fun of my friend in a discord call and I typed to him in in game chat, was just joking around, didn't know it would be an auto-ban.

**Comment by ToxicSnow** [comment]
The ban has been removed, and replaced with a 3 hour mute. try not to repeat the same offence
