### ISSUE TITLE
Bug: Died randomly whilst flying with elytra

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#13]
**Minecraft username**: JokerBoss99

* Expected behavior**: Be able to fly with an elytra without dying

**Actual behavior**: Get lagged back to the spot where I took off from the elytra, and instantly die.

**How can this issue be replicated?**: Not quite sure, I'll keep you updated if it happens again. Other players have been frequently getting flagged for flying today as well.

* A screenshot / video link if available**: 
![image](https://user-images.githubusercontent.com/49373976/56473256-88582380-6436-11e9-924b-381f4f39ea7f.png)

**Additional information**: Nope

**Comment by Kyrobi** [comment]
Has been potentially been fixed. If this occurs again, re-open this issue.
