### ISSUE TITLE
Ban Appeal: Silver_Stevie

### ISSUE THREAD

**Issue by SilverStevie1** [Kyrobi/Cynagen#130]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Silver_Stevie

**I was banned on**: March 08 20

**I was banned by**: Console

**I was banned for**: Saying no no word

**A brief summary of what happened before the ban was**: So I walk around with a cosmetic head named "Camel Cigs" and pass it around. Now, I developed a bad habit thanks to british friends, and some times use a word that I shouldn't be using to say them. So I will pass the head to someone "Take a ciggaret and pass it back" But i tend to shorten it because 1) I am lazy, and 2) I cant spell if my life depended on it. This time my brain decided to call them not cigs but something else

**I like to be unbanned because**: I really wrote that without remembering that word was a slur. My mind just completly blanked. This is my first punishment, and I have no intention of breaking other rules on the server. Or this rule again. Now this was just a brain blank at the wrong moment.

**Explain why is cereal is/isn't considered a soup**: Firstly we need to start with defining what is a soup.
According to Merriam-Webster:"a liquid food especially with a meat, fish, or vegetable stock as a base and often containing pieces of solid food"
According to Dictionary.com: "a liquid food made by boiling or simmering meat, fish, or vegetables with various added ingredients."
According to Oxford: "a usually hot, liquid food made from vegetables, meat, or fish:"
So with these definitions we defeinetly see some similarities. So one will need to come up with a checklist on what makes a soup.
-Liquid Base: Cereal has a liquid base.
-Some sort of Stock: Milk is not a stock. Claim it is and pray french chefs don't murder you in your sleep.
So cereal cannot comply to the 2 basic requirements of a soup, therefore, cannot be considered a soup.

**Additional information**: (Optional)

**Comment by ShoopyWhoopy** [comment]
milk is a stock fight me

**Comment by Kyrobi** [comment]
👍
