### ISSUE TITLE
Ban Appeal: NiamhLeah

### ISSUE THREAD

**Issue by NiamhLeah** [Kyrobi/Cynagen#131]
**Username**: NiamhLeah (and my friend Jahhson)

**I was banned on**: 2020-03-10

**I was banned by**: ColtCrohnie 

**I was banned for**: X-Ray

**A brief summary of what happened before the ban**:  i was playing normally on the server with my friends, just mining and building a farm for our base at around 11pm last night however when i came on today i have recieved a ban saying that i was xraying but i dont have any hacks installed onto my game. My friend Jahhson was also banned for the same reason.

**I like to be unbanned because**: I believe this was an unfair ban as i didn't do what i was stated to do

**Explain why is cereal is/isn't considered a soup**: bruv cereal isn't hot so it isn't a soup silly boi. Idk what kind of cereal youse are eating if you think its a soup cuz a soup has meat and vegetables and the cereal i eat clearly doesn't have either of them in

**Additional information**: (Optional) Also my friend Jahhson was banned for the same reason and he doesn't have any hacks installed to his game either

**Comment by NiamhLeah** [comment]
![image](https://user-images.githubusercontent.com/62070006/76441233-ff800880-63b6-11ea-914d-1a1f30f953fc.png)

**Comment by NiamhLeah** [comment]
![image](https://user-images.githubusercontent.com/62070006/76441334-250d1200-63b7-11ea-9223-31b7d867d165.png)

**Comment by ColtCrohnie** [comment]
![unknown](https://user-images.githubusercontent.com/50608164/76474170-c8b2ee00-63c8-11ea-9458-a755bccb443e.png)
![unknown](https://user-images.githubusercontent.com/50608164/76474176-ca7cb180-63c8-11ea-84bc-5420f067d420.png)

You and Jahhson mined out nearly every diamond ore in the area, and as you can see from the screenshots (source: #evidence chat via Discord server) that your tunnels do not follow the patterns of a legitimate player, as they lead directly to ore at nearly every turn.

If you two would like your appeals to be taken seriously, you need to think about telling the truth...

**Comment by NiamhLeah** [comment]
ok ill admit that used a texture pack that must have been glitched as it let me see through walls so i admit that i did use that texture pack in order to get diamonds once however Jahhson didn't, so could you please at least unban my friend as he is telling the truth when he says he didn't use xray. I am sorry for using this texture pack to cheat. I would appreciate it if you did give me another chance as i promise to not use this texture pack on your server again, you can remove the remaining diamonds from the chests in our base but could you please give me another chance, and unban my friend who wasn't involved in this at all as well. Sorry.

**Comment by StanLeeBigFan** [comment]
I vote you unban his friend and take diamonds up to you tho

**Comment by ColtCrohnie** [comment]
Well there's no glitch with texture packs that let's you see ore through stone unless it's a dedicated x-ray texture pack. Just don't use it again or you'll be permanently banned from the server with no appeal. You are unbanned, your x-rayed minerals have been confiscated.
