### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Chrizpot** [Kyrobi/Cynagen#133]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: _TheScareCrow_

**I was banned on**: March 03 2020

**I was banned by**: Kyrobi

**I was banned for**: Hacking - Speed / Jesus

**A brief summary of what happened before the ban was**: I was playing PvP with my friend Prohamgoose, following the rules of the server as per usual.

**I like to be unbanned because**: I never hacked and I don't know how to hack

**Explain why is cereal is/isn't considered a soup**: Soup is hot and typically consists of a vegetable broth of some kind. You often eat cereal for the grain and not the milk primarily. You always eat soup for the S O U P. Cereal could be considered a stew.

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
I apologize for the mistake. You are unbanned.
