### ISSUE TITLE
Ban Appeal:  Unnamed_Noodle

### ISSUE THREAD

**Issue by UnnamedNoodle** [Kyrobi/Cynagen#134]
**Minecraft username**: Unnamed_Noodle

**I was banned on**:  (March) 3/13/2020

**I was banned by**: The system i am guessing since it was a private msg.

**I was banned for**: Saying the word fag in a message.

**A brief summary of what happened before the ban was**:  I wasn't really thinking much cause i'm gay and i joke with that word a lot and i was trying to be funny and say i was listen to that kinda of music but i wasn't really thinking about how the server would react to that so with that i said what i said without thinking cause i wasn't using it in a harmful was i was just trying to be funny.

**I like to be unbanned because**: I am very sorry . It was 100% my fault for not even thinking about it and saying it anyway without knowing if it was allowed period i should've looked at the rules. 

**Explain why is cereal is/isn't considered a soup**:  Cereal is not a soup because soup usually has a broth and milk is not a broth.

**Additional information**: (Optional)
I am very sorry about saying it regardless if it was to be offensive or if it was a joke. Absolutely understand it was my fault for not reading the rules and will no longer be in my vocabulary or used on your server ever again.

**Comment by UnnamedNoodle** [comment]
if you would like a screenshot of what i said i will post it.

**Comment by Kyrobi** [comment]
Now that you know, try to not do it again. You are unbanned.
