### ISSUE TITLE
Ban Appeal Trashboats

### ISSUE THREAD

**Issue by Trashboats** [Kyrobi/Cynagen#136]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Trashboats

**I was banned on**: November 2nd 2019

**I was banned by**: Kyrobi

**I was banned for**: Tp Killing

**A brief summary of what happened before the ban was**: I was teleporting to a player, ive forgotten the name but I would tpa to them and kill them after they reported me then I was banned even though they were accepting the teleport requests

**I like to be unbanned because**: This was months ago and I want to come back to the server to see what its like

**Explain why is cereal is/isn't considered a soup**: Cereal is technically a soup since all it is, is a mixture of solids and liquids, most people think soup has to be warm and cereal cold but this isn't the case

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
You are unbanned. Please review the rules to avoid problems in the future.

https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md
