### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Peace135** [Kyrobi/Cynagen#137]
Please title this post "Ban Appeal:" followed by a name

**Peace135**

**March 13 2020**

**Kyrobi**

**I was banned for**: Flying/Hacking

**A brief summary of what happened before the ban was**: I was playing and idk but i left and a couple weeks later I want to rejoin and Im banned.

**I like to be unbanned because**: I wasn't hacking

**Explain why is cereal is/isn't considered a soup**: Well cereal isn't soup because when you tell someone your eating cereal your not eating soup. 

**Additional information**: (Optional) I WASN'T HACKING NOR FLYING WTF

**Comment by Peace135** [comment]
y would you suspect me

**Comment by Kyrobi** [comment]
Apologies, it was a mistake. You are now unbanned.

However, you have a terrible sense of time. 
You joined the server on March 13, 2020, and got banned on March 14, 2020, so I don't really know how you stopped playing for a **couple of weeks**.
