### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Trashboats** [Kyrobi/Cynagen#139]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Trashboats

**I was banned on**: March 27th 2020

**I was banned by**: ColtCrohnie

**I was banned for**: xray

**A brief summary of what happened before the ban was**: You recently banned a player known as meek_mills for x-raying, this is not me its another person in our household that shares the same ip as me which means I was banned for something he did, I hope you can unban me and I apologize for any problems

**I like to be unbanned because**: I was banned for something I didn't do

**Explain why is cereal is/isn't considered a soup**: cereal is a heterogenous mixture of 2 or more parts also you can see that there are 2 individual parts to it which means cereal is a soup.

**Additional information**: (Optional)

**Comment by ColtCrohnie** [comment]
You are unbanned. meek_mills will remain banned.
