### ISSUE TITLE
Other eewalktub

### ISSUE THREAD

**Issue by eewalktub** [Kyrobi/Cynagen#14]
Please title this post: "Other:" followed by a name.

Template:
####################

eewalktub

I'm getting rid of the stuff Snow gave me as soon as I get on today.

(Snow didn't just flat out GIVE it to us, he made like a mini dungeon and we survived and that was our reward. Blue told you because she was spiteful towards Snow. I understand what he did wasn't exactly fair and I will comply but it's important to note that it wasn't a flat out gift. Thank you
-\

**Comment by Kyrobi** [comment]
Understood. If later on you would like to open a private issue, you can simply use Discord and type `*new* into chat. This will bring up a private chat channel.
