### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Trashboats** [Kyrobi/Cynagen#140]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Trashboats

**I was banned on**: March 27th 2020

**I was banned by**: Succubi_Snow

**I was banned for**: "Get around this with your alt asshole"

**A brief summary of what happened before the ban was**: My younger brother was x raying on the server a few hours before I'm posting this and he got banned, we share the same ip so I got banned as well, I already stated this before and I got unbanned, I guess another mod thought it was an alt and banned me again, which is completely unfair because 1 you have no proof that its my alt and 2 my younger brother was x raying so this is not my fault, its not an alternate account he uses the same Wi-Fi as me which means we both share the same ip.

**I like to be unbanned because**: I was originally banned for something I didn't even do and a few hours later I'm banned and accused of using and alternate account, just because we have same ip addresses does not mean its an alt, before you ban someone you should have solid evidence that gives your the reason to ban me

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: If you wish to contact me through discord please do so at Trashboat500#7278,

**Comment by SinisterOwl** [comment]
Although it may be that you are only the brother of meek_mills, meek has also already said they have an alt and an ip ban seemed pertinent; not to mention it is difficult to verify that meek isn't using your account. Moreover, you do not exactly have a clean record yourself (accessable at http://cynagen.xyz/bans/history.php?uuid=4170dcaa56c248118957ab180f5cebb8&from=bans) -- so it seems gratuitous to go so out of their way for you who *might* be merely an innocent brother of meek.
That said I am merely a pointless meddlesome bystander myself -- the above is only a sentiment I caught from staff saying they were just going to go ahead and ip ban meek (and you by proxy).
