### ISSUE TITLE
Ban Appeal: Blu2thYT

### ISSUE THREAD

**Issue by Blu2thYT** [Kyrobi/Cynagen#142]
**Minecraft username**: Blu2thYT

**I was banned on**: March 29th 2020

**I was banned by**: Console

**I was banned for**: Renaming a stick N*gger Whacker 3000

**A brief summary of what happened before the ban was**: I was hitting my villagers with a stick to try to get them into a hole, and thought it would be funny to rename my stick. As soon as I took it out of the anvil I was instantly banned.

**I like to be unbanned because**: I love the server and the people on it. I donate often and I am an active member.

**Explain why is cereal is/isn't considered a soup**: Depends, are we talking about the milk or the cereal itself? The milk I would say is a broth and the cereal is the contents of the soup.

**Additional information**: Oof.
**Edit**: Spelling

**Comment by Kyrobi** [comment]
As a VIP and someone who enjoys the server, you should be aware of what's allowed and not allowed on the server.

Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by Blu2thYT** [comment]
I broke Rule #  3, section B.
If technicalities are involved, I guess you could also Rule # 4 section A broken.
Obviously Rule # 6 section B was broken.

**Comment by Kyrobi** [comment]
Please try to NOT do something like this again. Your permanent ban has been reduced to 3 days.
