### ISSUE TITLE
Ban Appeal: joshwatson123

### ISSUE THREAD

**Issue by joshwatson123** [Kyrobi/Cynagen#144]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: joshwatson123 and EdgeOfDusk

**I was banned on**: April 5 2020

**I was banned by**: (Leave blank if unknown)

**I was banned for**: i was testing the servers rules with naming items on a alt account just incase i broke a rule and got banned and when i got banned on my alot for renaming a piece of rotten flesh nLgger i was banned on both accounts.

**A brief summary of what happened before the ban was**: i was testing the auto ban system

**I like to be unbanned because**: i enjoy the sever and the community, i have many friends that play this server and they don't want to play on the server if we cant all play together

**Explain why is cereal is/isn't considered a soup**: isnt becuase who puts milk in soup

**Additional information**: joshwatson123 is my main account and EdgeOfDusk is my alt, if only joshwatson123 is unbanned id be perfctly ok with that

**Comment by Kyrobi** [comment]
The test worked and both of your accounts got banned. This feature is working as intended. Thanks for participating.

**Comment by joshwatson123** [comment]
wow k then

**Comment by joshwatson123** [comment]
btw no rules that say you cant rename a item a curse word

**Comment by Kyrobi** [comment]
Take a look at rule 3 section b: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md#3-be-respectful-to-everyone
