### ISSUE TITLE
Ban Appeal: unban me ffs i didnt offend any player and didnt break any listed rules

### ISSUE THREAD

**Issue by joshwatson123** [Kyrobi/Cynagen#145]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Take a look at rule 3 section b: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md#3-be-respectful-to-everyone

**Comment by joshwatson123** [comment]
its piece of rotten flesh that dosent even say anything bad, in just want to play the server

**Comment by Kyrobi** [comment]
The n word isn't bad? You clearly knew it was bad or else you wouldn't have used an alt to "test the ban system."

You're banned will be reduced to a 5 day ban.

**Comment by Kyrobi** [comment]
Your*

**Comment by joshwatson123** [comment]
thank you so much, but i didnt actully wright the n word
