### ISSUE TITLE
Ban Appeal: C0p3rnicus

### ISSUE THREAD

**Issue by C0p3rnicus** [Kyrobi/Cynagen#146]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:C0p3rnicus

**I was banned on**: (Format: Dec 23, 2012)
april 8, 2020

**I was banned by**: (Leave blank if unknown)
Succubi_snow

**I was banned for**:
Mass grief/raiding

**A brief summary of what happened before the ban was**:
I was Fishing? I really don't know why I was banned

**I like to be unbanned because**:
I had plans to expand my base, and play with my friends

**Explain why is cereal is/isn't considered a soup**:
A quick google search shows that soup is defined as "a liquid dish, typically made by boiling meat, fish, or vegetables, etc., in stock or water". cereal isn't hot, unless your a psychopath who eats hot cereal.

**Additional information**: (Optional)
all friends i was playing with were also banned for the same reasons

**Comment by ToxicSnow** [comment]
Okay, well I apologize for banning you, I grabbed your username from the trust list bc a group of your friends were going around and stealing from other houses around the area. U are unbanned. however if you want the others to get unbanned they have to do their own appeals.
