### ISSUE TITLE
Ban Appeal: gotstyle65

### ISSUE THREAD

**Issue by gotstyle65** [Kyrobi/Cynagen#148]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: gotstyle65

**I was banned on**: April, 8 2020

**I was banned by**: Sccubi_Snow

**I was banned for**: Greifing

**A brief summary of what happened before the ban was**: I took part in stealing from a house which was not claimed. I had assumed that since it was unclaimed, that it had been abandoned.

**I like to be unbanned because**: I feel that I have learned from this incident and it has made me a better person. I have never been one to make assumptions like this, but since my city has been under lockdown, Minecraft has been the only way I have been able to be with my friends. over the past couple of days we have been building a house together and its been the most fun I've had in ages. Thank you :)

**Explain why is cereal is/isn't considered a soup**: It's milk and not broth

**Additional information**: I just wanted to say that you for being such good admins. You make this server so great :)

**Comment by ToxicSnow** [comment]
![2020-04-08_20 40 23](https://user-images.githubusercontent.com/44278156/78850766-0154e000-79e6-11ea-9f32-56b26d0ec60a.png)
As I said with Rwade, The first rule says no griefing, claimed or not. We were looking into when they went into another players house and stole items. when we checked the logs of those chests, we found out that it wasn't the first time that they had stolen from the house, we then took harder look and noticed that all the houses around your little community were stolen from and were continuing to be stolen from by your friends and you.

And furthermore please read the rest of the rules, and the extended copy of them on this site, as it goes into further detail for the rules. Also, your ban was also reduced to 1 day vs the 14.

**Comment by gotstyle65** [comment]
Thank you, I will be sure to read the rest of the rules
