### ISSUE TITLE
Ban Appeal: DanyalCook

### ISSUE THREAD

**Issue by DanyalCook** [Kyrobi/Cynagen#149]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: DanyalCook

**I was banned on**: April 8, 2020

**I was banned by**: Kyrobi

**I was banned for**: Cheating - Killaura / Step

**A brief summary of what happened before the ban was**: I was playing in VR and that was it.

**I like to be unbanned because**: I did no such cheating/hacking only was playing in VR. I can prove I own a VR.

**Explain why is cereal is/isn't considered a soup**: Because the name of the dish is Cereal

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Sure. Include a picture of your VR

**Comment by DanyalCook** [comment]
![20200408_211231_HDR](https://user-images.githubusercontent.com/63382122/78850803-bcc54680-79dd-11ea-8186-0dc760546923.jpg)

**Comment by Kyrobi** [comment]
Could you give cite / source to where to managed make it work with 1.15 since ViveCraft only works 1.14.

**Comment by DanyalCook** [comment]
They did update it for 1.15
http://www.vivecraft.org/downloads/

**Comment by DanyalCook** [comment]
![1 15](https://user-images.githubusercontent.com/63382122/78851002-53920300-79de-11ea-97c6-0c5c1d7bc89e.PNG)

**Comment by Kyrobi** [comment]
You are unbanned.
