### ISSUE TITLE
Slow falling potions broken

### ISSUE THREAD

**Issue by Nightawkdude** [Kyrobi/Cynagen#15]
Expected behavior: Slow falling effect causing you to descend slowly. 
Actual Behaviour: Slow falling causes you to stay in one place and glitch in place while randomly taking damage.
To replicate: drink a potion and jump off of something or pillar up and break blocks below yourself.

**Comment by Kyrobi** [comment]
Finally! Someone who actually included details on how to replicate the issue! Can confirm that this is an issue. Will look into it.

**Comment by Kyrobi** [comment]
Probably fixed,
