### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Modletoast27711** [Kyrobi/Cynagen#151]
Please title this post "Ban Appeal:" Modletoast27711**Minecraft username**:

**I was banned on**: (Format: Apr 08, 20

**I was banned by**: 

**I was banned for**: Griefing

**A brief summary of what happened before the ban was**: I was walking around and had found an unclaimed house. I begun to explore the house and enjoyed the ascetic so I was going to leave a sign saying that the house was neat. I was then unexpectedly banned for 13 days.

**I like to be unbanned because**: I have been enjoying time with my friends during the pandemic and it is one of the only ways I can hangout with them and I don't feel that my ban was justified.

**Explain why is cereal is/isn't considered a soup**: Cereal is a soup because it has a liquid broth (milk) and a main course (cereal)

**Additional information**: (Optional) Ya'll pretty cool

**Comment by ColtCrohnie** [comment]
After looking at the house you "visited" the logs revealed you stole from their chests, broke their windows, etc. There were multiple places where this occurred where you and your friends would go on "crusades" and raid the local bases near yours. Next time please be honest.

**Comment by Modletoast27711** [comment]
My minecraft name is Modletoast 27711, I
 wanted to apologize to you directly for grieving. I was walking around
your awesome server when I stumbled upon a house that was unclaimed. My
speculation was if houses were unclaimed they were vacant and I begun to
check out the house. I was unaware that unclaimed houses could still have
someone living in the house. I have read over the rules of the server
during my ban and now understand what I have done is wrong I will fix and
replace anything that was tampered with in the house. Me and my friends now
fully understand the rules of the server that has been nothing but nice to
us and will pay the people on this server with more respect.

**Comment by Modletoast27711** [comment]
I’m sorry for the spamming of the ban appeals but all of my other friends
got appealed which some such as rwade2126 are more guilty than me. I have
read the rules over and fully understand the perimeters. I would very much
like to return playing with my friends and promise to leave you alone
immediately. I just don’t see why this is such and issue when it can easily
be resolved and we can all be happy.

( this is a reply to the previous email)

**Comment by ColtCrohnie** [comment]
But in your first appeal, it was unorganized, improper, and untruthful thus your appeal was denied.

All of your appeals are denied, continuing to bother staff about this will result in a 30 day extension of your initial ban. Please wait the remaining 10 days 6 hours for your current ban to expire before continuing to play.

This is your final warning.
