### ISSUE TITLE
Ban Appeal: Modletoast27711

### ISSUE THREAD

**Issue by Modletoast27711** [Kyrobi/Cynagen#153]
Please title this post "Ban Appeal:" 

**Minecraft username**: Modletoast27711

**I was banned on**: (Format: Apr 8, 20

**I was banned by**: (Leave blank if unknown)

**I was banned for**: Mass grieving and raiding

**A brief summary of what happened before the ban was** I was traveling the server "going on a crusade" which was where we go about claiming unclaimed land I came upon an unclaimed house. I thought if houses were not claimed that the owner stopped playing on the server and it was abandoned. After being banned I read the rules and found that even if it is unclaimed that it still belongs to someone and could still be living in the house.

**I like to be unbanned because** I now understand why grieving any house is unmoral and against the rules and I would like to apologize and show I have learned my lesson. Under your permission I would like to return to playing on your great server with my friends during these crazy times.  

**Explain why is cereal is/isn't considered a soup**: cereal by its self is not a soup because you need a broth but if you added milk to the cereal then it would be a soup with a broth and contents of cereal.

**Additional information**: I am very sorry for grieving a house that was not claimed and I now know that I should not and have learned my lesson.

**Comment by ColtCrohnie** [comment]
Please don't make more than one ban appeal.

**Comment by Modletoast27711** [comment]
My b
