### ISSUE TITLE
Ban Appeal: Modletoast27711

### ISSUE THREAD

**Issue by Modletoast27711** [Kyrobi/Cynagen#156]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Modletoast27711

**I was banned on**: Apr, 8, 20

**I was banned by**: Succubi_Snow
**I was banned for**: Mass grieving 

My minecraft name is Modletoast 27711,

 I was walking around your awesome server when I stumbled upon a house that was unclaimed. My speculation was if houses were unclaimed they were vacant and I begun to check out the house. I was unaware that unclaimed houses could still have someone living in the house. I have read over the rules of the server during my ban and now understand what I have done is wrong I will fix and replace anything that was tampered with in the house. Me and my friends now fully understand the rules of the server that has been nothing but nice to us and will pay the people on this server with more respect.

**Explain why is cereal is/isn't considered a soup**: Cereal is a soup if milk is added because the milk is a broth and the cereal is the contents of the soup.

**Additional information**: I know you said that I should not file more than one ban appeal but I am very sorry and now fully understand the rules of this awesome server. I would very much enjoy reconnecting with my friends on your awesome server and promise to pay the people on your server with respect and become a rule abiding player.

**Comment by ColtCrohnie** [comment]
This is the forth ban appeal you've opened after being told not to, continute and I'll extend your ban by 30 days.
