### ISSUE TITLE
Ban Appeal: RealEyez

### ISSUE THREAD

**Issue by RealxEyez** [Kyrobi/Cynagen#157]
**RealEyez**:

**I was banned on**: April 13 2020

**I was banned by**: Console 

**I was banned for**: "Saying an explicit word"  

**A brief summary of what happened before the ban was**: Randomly typed in text and I accidentally typed in a word that is banned 

**I like to be unbanned because**: It was a complete accident and I wouldn't actually say something that offensive 

**Explain why is cereal is/isn't considered a soup**: Cereal IS a soup and I'll tell you why. A quick Google search shows that soup is a liquid dish, and the definition of cereal is a grain used for food. So if I were to say that cereal is not a soup, then if I were to go put some rice corn or any other grain then that means its no longer soup. Which makes no sense. Along with that cereal does have liquid content in it which is milk, so because you CAN put grain in your soup and you CAN have milk in your cereal which is a liquid, this means that I completely wasted my time by writing all this out in one go without looking back at any spelling or grammar mistakes oh god I want this corona virus to go away so I can go back to my job and get money so I don't have to worry about not being able to pay rent. 

**Additional information**: (Optional)
![Screen Shot 2020-04-13 at 7 24 38 PM](https://user-images.githubusercontent.com/63625252/79179866-6c732d80-7dbd-11ea-880f-f55121cb7221.png)

**Comment by Kyrobi** [comment]
Resolved
