### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by slayaphobia** [Kyrobi/Cynagen#159]
Please title this post "Ban Appeal:" followed by a name

Minecraft username: slayaphobia

I was banned on: April 18, 2020, 07:03

I was banned by: ColtCrohnie

I was banned for: Broke Rule 5 - X-Ray

A brief summary of what happened before the ban was: I was getting diamonds (and yes I was using xray) and then the mod talked to me and explained to me it wasn't allowed.

I like to be unbanned because: I didn't realize that it was bannable on the server. I feel really bad, and I will never do it again.

Explain why is cereal is/isn't considered a soup: This isn't a soup because I really didn't know it was a rule. I'm very sorry.

Additional information: (Optional)

**Comment by ColtCrohnie** [comment]
Your ban has been reduced to 5 days, please take the time to read the rules in detail here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md
