### ISSUE TITLE
Bug: Gloor Clip

### ISSUE THREAD

**Issue by eewalktub** [Kyrobi/Cynagen#16]
eewalktub

* Expected behavior**: Elytra not yeeting you like 30 blocks under the ground

**Actual behavior**: Elytra yeets you like 30 blocks under the ground

**How can this issue be replicated?** By being yeeted by Elytra 30 blocks under the ground

* A screenshot / video link if available**:

**Additional information**: It happens anywhere. Even the End. Had I not had frieworks I would have lost a lot.

**Comment by Kyrobi** [comment]
Probably fixed.

**Comment by eewalktub** [comment]
Thank you
