### ISSUE TITLE
Ban Appeal: ThatGuySky01

### ISSUE THREAD

**Issue by SkyMan6291** [Kyrobi/Cynagen#160]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: april 21 2020)

**I was banned by**: (Colt)

**I was banned for**: X ray

**A brief summary of what happened before the ban was**: wasnt online when the ban happened 

**I like to be unbanned because**: you guy know me and i really enjoy the server. ive paid for vip so i obviously enjoy playing n your server

**Explain why is cereal is/isn't considered a soup**: soup is hot, cereal is not nuff said

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Hey, we're taking it as a coincidence ... although a really suspicious one. You're unbanned. Please do not perform such mining techniques to prevent being banned in the future.
