### ISSUE TITLE
Ban Appeal: Bloodbaths 

### ISSUE THREAD

**Issue by Bloodbaths** [Kyrobi/Cynagen#161]
**Minecraft username**: Bloodbaths

**I was banned on**: 4/21/20

**I was banned by**: system

**I was banned for**: accidently saying the n word when messaging a friend

**A brief summary of what happened before the ban was**: my friend was typing to me through the private message system in the server when I messaged him, I didn't realize that i could get banned through privately messaging my friend by saying the n word, i wasn't really using my brain and i had no intent to damage the server in any way and I just wasn't thinking and didn't realize i could get banned through the private message system. 

**I like to be unbanned because**: Because it was by accident, I really love that server and I would play on it almost every day, I put a lot of work into it with my friends and I didn't realize what I could say through private message between friends could get me banned. I should of read the rules before anything and i should, in general, not say those kinds of things, I'm sorry.

**Explain why is cereal is/isn't considered a soup**: ok, first of all, cereal is not hot, does not contrain meat NOR VEGETABLES, therefore, It is only through deductive reasoning that leads the to conclusion that CEREAL is in fact NOT a soup, thank you. 

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: Hello! I broke Rule #1 Section H

Once you have replied, your application will further proceed.

**Comment by Bloodbaths** [comment]
Hi! I broke Rule #3b

**Comment by cottoncandyowo** [comment]
I lifted you ban and changed it to a 2 day mute, thank you for waiting patiently and next time don't say it :p
