### ISSUE TITLE
Ban Appeal: arock69

### ISSUE THREAD

**Issue by arock69** [Kyrobi/Cynagen#162]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: arock69

**I was banned on**: April, 27 2020

**I was banned by**: ColtCrohnie

**I was banned for**: Rule 5 - Xray

**A brief summary of what happened before the ban was**: I used an xray pack on the Cynagen minecraft server.

**I like to be unbanned because**: My whole life I have been someone who never does anything wrong. I used to get nervous bringing food into the movie theatre. My whole life, I though of myself as a rule follower. I recently changed schools and moved away from all of my friends to study at a magnet school, where the classes were harder and more competitive. To this day, I still hear from my friends that I should transfer back, but now I have invested myself into this school and I cannot just get up and move. But the truth is, I would like to come back and be with my friends, but I can't. And the truth is, this new school is pretty hard and it's kind of kicking my butt, but I can't give up. Honestly, I don't really care if you unban me. I have been pondering on this for a year and I really just needed somewhere to write it down. For someone to listen to my struggles. But I really don't think my struggles are that bad and I have it pretty good. Also I'm happy and content. So, no matter what you decide to do, I'm just glad you listened. That you care enough to read a page out of the book that is my life. Thanks :)

**Explain why is cereal is/isn't considered a soup**: its not hot probably

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Your ban has been lifted
