### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by auspiciousfaxer** [Kyrobi/Cynagen#163]
Please title this post "Ban Appeal:" followed by a name

auspicious_faxer:

**I was banned on**: April 29, 2020

**I was banned by**: ColtCrohnie

**I was banned for**: X-Ray usage

**A brief summary of what happened before the ban was**: I did ./wild and mined with much profit

**I like to be unbanned because**: I was not using x-ray :(

**Explain why is cereal is/isn't considered a soup**: The Oxford Dictionary defines soup as "a liquid dish, typically made by boiling meat, fish, or vegetables, etc., in stock or water." One does not boil meat, fish, nor vegetables in a stock or water whilst preparing cereal.

**Additional information**: *None*

**Comment by ColtCrohnie** [comment]
The image below are the tunnels that show your x-ray patterns.

![Inked2020-04-29_11 15 21_LI](https://user-images.githubusercontent.com/50608164/80619823-d5d47c80-8a0a-11ea-866b-20e410fb04ec.jpg)

The circled areas indicate where you mined diamonds, with tunnels leading to each one, I also moderated you and watched you mine the diamond ore on the bottom left.

**Comment by auspiciousfaxer** [comment]
Wow, it's been a while. Time to come clean. No, I was not using x-ray but yes, I was obtaining them in an unhonest manner. Even if I don't get unbanned, I apologize for breaking the rules, and thanks for the short-time acquaintances I got to meet on the server.

**Comment by ColtCrohnie** [comment]
Your ban has been reduced to 4 days, next time please don't lie in your appeal.

Please update yourself on the rules until your ban has expired.

https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md
