### ISSUE TITLE
Ban Appeal: wailfullmoon2_0

### ISSUE THREAD

**Issue by wailfullmoon6057** [Kyrobi/Cynagen#166]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: wailfullmoon2_0

**I was banned on**: (May 3, 2020)

**I was banned by**: 

**I was banned for**: I hacked but im sorry

**A brief summary of what happened before the ban was**: i was testing a hacked client for a youtube review of wurst client and i got banned

**I like to be unbanned because**: i just wanted a sub scriber and im sorry

**Explain why is cereal is/isn't considered a soup**:  i dont get what this means

**Additional information**: sorry i wont do it again :C

**Comment by Kyrobi** [comment]
![IMG_20200402_133207](https://user-images.githubusercontent.com/20980266/81596574-ef21e500-9389-11ea-9cec-2cadb4bfd923.jpg)

**Comment by Kyrobi** [comment]
That is sooo sad

**Comment by wailfullmoon6057** [comment]
shut up kyrobi.

**Comment by wailfullmoon6057** [comment]
plz let me come back to cynagen i will never do it again
i promise

-wailfullmoon6057


i got new username btw its xXwailXx

**Comment by JokerBoss99** [comment]
> plz let me come back to cynagen i will never do it again i promise
> […](#)
> -wailfullmoon6057 i got new username btw its xXwailXx

Hi, could you please tell me why my wife left me and took the kids? I've been contemplating this for a while and I don't know. If you could tell me why they left, then I might be able to unban you

**Comment by wailfullmoon6057** [comment]
umm.. well describe what you did before your wife left you.
maybe you yelled too much
maybe you didint spend enough time with the family. just describe what you
did and il find where you messed up.

**Comment by wailfullmoon6057** [comment]
also here is a big one: maybe you were playing too much minecraft.
i dont really have any details to work with soooooooooo plz describe what u
did before they left u

**Comment by wailfullmoon6057** [comment]
i may have completely figured it out, this is only a guess. maybe its
because you were playing on a minecraft dating server, duh! that has
cheating written all over it.

**Comment by cottoncandyowo** [comment]
Can you help me become more flamboyant??? My girlfriend told me I'm not cool enough and she won't hold my hand because I have HIV positive. So I told her to go make me a sandwich and she broke up with me :( Please I want her back please what can I do to become more flamboyant..

**Comment by wailfullmoon6057** [comment]
as an actor i say look up how to be an actor. also wanna get cooler? dont
be all like hey dewd wasuup dude bro lit hype. that will get you in a MUCH
worse situation. yeesh, sounds like a demented fidget spinner had a child.
also apolagise for saying go make me a sandwitch.   there go be cool and
also no idea what flamboyant means but hey, there is always wikihow.
another tip is work on kindness (not that ur not already kind) but if you
manage to get very very kind, she might like you. hiv thing, just wear a
mask and gloves. if this dosent work, sorry i tried :(.

**Comment by wailfullmoon6057** [comment]
*nalyze why you want to get back together.* Getting back together with your
boyfriend because you are emotionally distraught may not be the best
reason. Breakups are hard but people recover from them all of the time.
Getting back together with him for financial security is also sure to end
badly.[1]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-1>
Before
you try to resume the relationship, take an objective look at your reasons
for separating and for wanting to get back together.

   - Discuss your reasons with trusted friends and family to get their
   perspective on the situation. While the decision is ultimately yours,
   getting an outside look at your relationship can help you figure out the
   reasons you want him back.
   - Make a list of pros and cons for getting back together. Also consider
   the positives and negatives of resuming the relationship versus staying
   single, as well as what would need to change if you got back together. For
   example, if you broke up because you didn't like one of his friends, you
   may need to get over those feelings in order to make the relationship work.
   - Don't let fear of the unknown or of never finding love again hold you
   back from moving on. Sometimes staying broken up is what's best, but it's
   hard to see that until you've gotten over the initial pain. It's normal to
   hurt after a breakup, even if it's the best decision.

**Comment by wailfullmoon6057** [comment]
sorry if it says boyfriend i just copy and pasted it :p
anything else i can do?

**Comment by wailfullmoon6057** [comment]
*Reflect on your role in the breakup.* It may be difficult to understand
that you had any fault in it at all. If he gave you his side of the story,
think about it with an open-mind. Relationships can be complicated and
sometimes you can withhold the needs of the other person without even
realizing it. Ask yourself:[2]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-2>

   - What worked in your relationship?
   - What didn’t work in your relationship?
   - What could you have done differently to positively affect your
   relationship?
   - Use these questions to build healthy relationships moving forward.

**Comment by wailfullmoon6057** [comment]
have more helpful information!

**Comment by wailfullmoon6057** [comment]
*Consider what changes can be implemented to improve the relationship.* Also
consider what changes you would like to ask your former partner to
implement. Ask yourself if it is worth getting back together if your ex is
not interested in making any changes.[3]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-3>

   - Be careful not to compromise who you are as a person just to get a guy
   to like you.

**Comment by wailfullmoon6057** [comment]
wikihow, you are on FIRE today

**Comment by wailfullmoon6057** [comment]
*Seek guidance from a friend, relationship coach, or therapist.* Find
someone that you trust to talk to about getting back together with your
ex-boyfriend. A third party may be able to see things that you are not able
to see. If you need serious help to deal with your emotions after a breakup
consider seeing a therapist.[4]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-4>

**Comment by wailfullmoon6057** [comment]
*Reflect on the good times in the relationship.* Remember why you fell in
love with that person. Long-term relationships are hard. Over time, it can
be difficult to see positive qualities in your significant other. You may
dwell on only the negative qualities. Make a list of all the positive
qualities and memories you have of your ex-boyfriend.[5]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-5>

**Comment by wailfullmoon6057** [comment]
Opening the Lines of Communication

**Comment by wailfullmoon6057** [comment]
*Meet in person.* After you have been talking for a while suggest that you
meet for coffee or lunch. Keep these meetings brief at first. Your goal is
to reminisce on good times that you had together and leave him with feeling
like he wants to see you more. As time progresses, you can start to
introduce lengthier dates.[7]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-7>

   - You should make your interest in getting back together clear in person.
   - Say something like, “I have been thinking about our separation a lot
   lately. I really miss our relationship and think that we might be able to
   make it work again.” only say this if u rlly can make it work again -wail

**Comment by wailfullmoon6057** [comment]
oops! this one is before that.


*Talk to him.* You won’t know if he wants you after the break up if you are
not communicating. Wait until the tensions and emotions have leveled out.
You can begin talking to him many different ways.[6]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-6>

   - Call, text, or reach out to him on social media.
   - Start the conversation by saying, “Hey! It’s been awhile since we have
   talked. What is new in your life?”

**Comment by wailfullmoon6057** [comment]
*Apologize for any wrongdoings.* Since you have already reflected on your
role in the breakup, you will have a good understanding of anything that
you did to contribute to the decline of your relationship. Own up to your
mistakes and apologize for them.[8]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-8>

   - Make yourself a little vulnerable. Say, “I’m sorry for not truly
   listening to you when you were trying to talk to me about our relationship.”

**Comment by wailfullmoon6057** [comment]
*Discuss each other's wants and needs in a relationship.* Be sure that you
understand what you want out of a relationship now and in the future, then
listen to what he wants. Communicate those desires clearly if you start to
talk about getting back together. If you do end up getting back together,
you want your boyfriend to have a clear picture of your needs so that you
are both on the same page. Additionally, you need to make sure that you can
meet his needs.[9]
<https://www.wikihow.com/Get-a-Guy-to-Want-You-Back-After-a-Breakup#_note-9>

**Comment by wailfullmoon6057** [comment]
*Give him some space.* If he makes it clear that he is not interested in
talking or being friendly, respect that

**Comment by wailfullmoon6057** [comment]
once again if this dosent work im super sorry, im just a nitwit who plays
minecraft
