### ISSUE TITLE
Ban Appeal: BigOleBobcat

### ISSUE THREAD

**Issue by BigOleBobcat** [Kyrobi/Cynagen#167]
Minecraft username: BigOleBobcat
I was banned on: (May 4, 2020)
I was banned by: Jokerboss99
I was banned for: X-ray
A brief summary of what happened before the ban was: I was looking through my texture packs and saw an x-ray pack from like 1.8 so I tried enabling it and used it for a couple minutes.
I like to be unbanned because: I have really enjoyed playing on the server and I regret trying the pack and will not do anything like it again.
Explain why is cereal is/isn't considered a soup: Well I don't eat much soup but I know cold soup is yucky and you don't want hot Capn Crunch!
Additional information: I apologize sincerely

**Comment by JokerBoss99** [comment]
Ban shortened to 2 days, please refresh yourself on the rules and make sure you don't do it again.
