### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Blizzrdz** [Kyrobi/Cynagen#168]
Please title this post "Ban Appeal:" Blizzrdz

**Minecraft username**: Blizzrdz

**I was banned on**: 2019-09-06
**I was banned by**:  Kyrobi
**I was banned for**: Xray

**A brief summary of what happened before the ban was**: I can't clearly remember exactly what happened, but I do remember that I was xraying because my foolish self was thinking that the best way to get some diamond armor was to xray them.

**I like to be unbanned because**: I would really appreciate it if I were unbanned because I completely regret everything I did, because after that happened my friends obliviously continued to play it while I couldn't do smp with them.

**Explain why is cereal is/isn't considered a soup**: Cereal is not a soup because as you can tell it is not hot and the dictionary even states, “a liquid food made by boiling or simmering meat, fish, or vegetables with various added ingredients.”

**Additional information**: (Optional)

**Comment by cottoncandyowo** [comment]
Good answer on the soup question, your ban was reduced to 3 days. Don't do it again or else you'll stay perm banned
