### ISSUE TITLE
Ban Appeal: Mr_Joeyy

### ISSUE THREAD

**Issue by Mrjoeyy** [Kyrobi/Cynagen#169]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:Mr_Joeyy

**I was banned on**: (May 06, 2020)

**I was banned by**: Succubi_snow

**I was banned for**:X-ray 

**A brief summary of what happened before the ban was**:
I found a lot of diamonds at once

**I like to be unbanned because**:

Hello! I would like to start off my saying I love playing on your Minecraft server. My name is Joey and I’m 20 years old, from Miami. 
I was mining and coincidentally found a lot of diamonds whithin 5 minutes. This is Probably why I was banned. 
The ban is for five days, I can wait five days, no worries, but I’m just writing this to clear my name. I would never hack or cheat, especially for diamonds. (I’m more into building, lol)

Thank you for your time

**Explain why is cereal is/isn't considered a soup**:
It is considered a soup because it’s surrounded by liquid (milk) and is served in a bowl, and you eat it with a spoon, soo...

**Additional information**: (Optional)

**Comment by ColtCrohnie** [comment]
You ban has been lifted, we apologize for the inconvenience.
