### ISSUE TITLE
Bug: Hoppers Slow af

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#17]
**Minecraft username**: JokerBoss99

* Expected behavior**: Hoppers to not overflow on basic mob farms

**Actual behavior**: Hoppers overflow on basic mob farms

**How can this issue be replicated?** Put anything in a hopper, it will take forever to transport

* A screenshot / video link if available**: N/A

**Additional information**: Just something to fix when you have the time

**Comment by Kyrobi** [comment]
I think this issue has been fixed a few days ago (speed increased by 2x). If it still persists and being "slow af", re-open this issue or make a new one.
