### ISSUE TITLE
Ban appeal iLemon_

### ISSUE THREAD

**Issue by demonzblood** [Kyrobi/Cynagen#170]
Please title this post "Ban Appeal:" followed by a name

iLemon_

I was banned on 5/10/2020

ColtCrohnie

AutoClicker

I was using autoclicker to mend my shovel in my zombie farm from xp

I would like to be unbanned because I was playing with my friends today and suddenly im banned and cant join back and this is like the only way me and my friends can play a survival and im not allowed to play on weekdays usually so I might have to wait another week to play

Cereal is not a soup because its not hot, and soup usually doesnt have 50% as something besides a liquid.

Before submitting this post, I wasn't aware of the rule stated in the screenshot. As of right now, I have read all of the rules and will no longer make these mistakes.

![ban](https://user-images.githubusercontent.com/54691727/81513162-22f20180-92db-11ea-88a4-ced60021ec9e.png)

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by Kyrobi** [comment]
Closed due to inactivity
