### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by SuperKillerBear** [Kyrobi/Cynagen#171]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:SuperKillerBear

**I was banned on**: (Format: Dec 23, 2012) May 5, 2020

**I was banned by**: (Leave blank if unknown)ColtCrohnie

**I was banned for**:Xray

**A brief summary of what happened before the ban was**:I was playing then got kicked, I tried to log back in, but It wouldn't let me. I tried for several days then It said I was banned

**I like to be unbanned because**: It is a shared account and my sibling uses it and admitted they xrayed to make money so they could buy some pets. I didn't know this and therefore feel like I should get a second chance. I feel responsible for my actions of not finding out sooner and not stopping it from hacking, trust me that it won't happen again.

**Explain why is cereal is/isn't considered a soup**:
Cereal is soup because it has food in it with a liquid, boom, a soup.
**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by SuperKillerBear** [comment]
Hello! I broke Rule 5. section c.

I understand that this is not acceptable, please unban me, it is my favourite server.

**Comment by Kyrobi** [comment]
Your ban has been lifted. Please be careful next time.

**Comment by SuperKillerBear** [comment]
THANK YOU SO MUCH YOU ARE A GOD THANKS THX THX THX!!! UR so kind, THX
