### ISSUE TITLE
Ban Appeal: TommyMiles0

### ISSUE THREAD

**Issue by TommyMiles0** [Kyrobi/Cynagen#175]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: TommyMiles0

**I was banned on**: (Format: May 29, 2020)

**I was banned by**: automod

**I was banned for**: saying https://en.wikipedia.org/wiki/Faggot_cell

**A brief summary of what happened before the ban was**: i posted the wiki page for faggot cells for tetro to look at

**I like to be unbanned because**: in the context of faggot cells, the word faggot is not a slur

**Explain why is cereal is/isn't considered a soup**: cereal is not considered soup as there is no mixing / blending  of several ingredients, the ingredients are distinguishable from each other when they are all in the bowl.

**Additional information**: (Optional)
ly ky no homo

**Comment by cottoncandyowo** [comment]
next time don't post that, its obvious that you'd get banned for that even if it isn't a slur. ill pardon your ban but mute you for 12 hours for being cringe
