### ISSUE TITLE
Ban Appeal: Ale1000skater

### ISSUE THREAD

**Issue by Ale1000skater** [Kyrobi/Cynagen#176]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Ale1000skater

**I was banned on**: May 29, 2020

**I was banned by**: server

**I was banned for**: "get the fuck off faggot" - friend

**A brief summary of what happened before the ban was**: a group of players were fighting with my friend and trying to kill us and just annoy us as much as possible.

**I like to be unbanned because**: my friend was the one that said that not me, we are just on the same network. He is Pruitmartialarts.

**Explain why is cereal is/isn't considered a soup**: because cereal has milk and soup has spices and water. Imma go eat soup now.

**Additional information**:  Cool server.

**Comment by cottoncandyowo** [comment]
Im going to take off the ban an instead mute you for a day, try not to say these types of things and you won't get banned again. If it does happen again you'll stay banned
