### ISSUE TITLE
Ban Appeal: Amelia

### ISSUE THREAD

**Issue by Kelish1366** [Kyrobi/Cynagen#177]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by Kelish1366** [comment]
Ban Appeal: AMelia. Kelish1366. I was banned on May 31, 2020. I was banned by the bot. We were talking about how another member was banned for saying the N word, and I said "If it makes you feel any better, i was banned on another server for saying "Nigghhttt". I was baned the moment I hit send, and i assume it is because the bot thught i said the same word. I would like to be nubanned because this is the only server i have enjoyed playing on and liked the people. I believe this was not a ban that had backing to it, it was the bot filtering a word i did not say.. 

please unban me i kinda love the server

**Comment by JokerBoss99** [comment]
Unbanned. Tell your friend to stop being stupid as well, thanks.
