### ISSUE TITLE
OTHER: My bud kelish was unjustly banned

### ISSUE THREAD

**Issue by oktead** [Kyrobi/Cynagen#179]
Please title this post: "Other:" followed by a name.

Template:
####################

**My Minecraft username**: oktead

**Description**:
ALSO
Kelish was autobanned for saying the n word but she actually said "nigght" or something like that. not cool

**Additional information**: (Optional)
hello again

**Comment by JokerBoss99** [comment]
Why tf would you open this just to close it? 
**Locked.**
