### ISSUE TITLE
Ban Appeal: I Genuinely did NOT grief anyones things 

### ISSUE THREAD

**Issue by jjujubee** [Kyrobi/Cynagen#18]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: jujubee_

**I was banned on**:  07/05/19

**I was banned by**: Cottoncandy_

**I was banned for**: "Griefing"

**A brief summary of what happened before the ban was**: Me and another person went to their village/town and then they started killing me, and I just wanted to take a proper look at their place for inspiration for builds, but COULDN'T because i was running away the whole time

**I like to be unbanned because**: I literally did NOT grief, nor steal anyone's things, and if they say I did, I was followed around by jmaster and he literally saw i didn't take anything. I also didn't grief their things, and if you don't believe me check the logs

**I often slap little kids because**: I can, and its their problem not mine xx

**Additional information**: I was seriously falsely accused of stealing and griefing but I did nothing of the sort

**Comment by ToxicSnow** [comment]
Okay From what I was able to pick up from the server and what was told to me by others, you had an attitude towards everyone, disrespectful, and just causing drama. Cotton also went by the area you guys were at and your friend broke a bunch of fences and fucked with Livys stuff. Also, I was told that you were both told to leave. I will probably check how much longer your buddy has left on his ban and make yours match, However realize that this isn't us being Biased or anything towards the other players, we're just picking up the data and judging accordingly.
