### ISSUE TITLE
Bug: Villagers disappearing

### ISSUE THREAD

**Issue by oktead** [Kyrobi/Cynagen#180]
Please title this post: "Bug:" followed by a name.

**Minecraft username**: oktead

**Expected behavior**: villagers... dont disappear

**Actual behavior**: they do disappear

**How can this issue be replicated?** 
having more than 20 villagers within 50 block radius 

**A screenshot / video link if available**:

**Additional information**: unsure if this is on purpose or not, but was told to put this here

**Comment by JokerBoss99** [comment]
@oktead Yep this is intentional, its to prevent massive villager farms lagging the server

**Comment by oktead** [comment]
OK, thanks bro
