### ISSUE TITLE
Ban Appeal: (underscore)Balanced(underscore)

### ISSUE THREAD

**Issue by Godspeed6969** [Kyrobi/Cynagen#186]
**Minecraft username**: (underscore)Balanced(underscore) because the underscores create italics

**I was banned on**: June 14, 2020

**I was banned by**: Console

**I was banned for**: Saying: "this nibba spittin"

**A brief summary of what happened before the ban was**: My friend had said something funny in chat, and I thought it would be funny if I said that in response. It was a complete joke, I was just referencing the popular meme.

**I like to be unbanned because**: I'm working on a building project right now and I kinda don't want to wait 2 days. Thanks anyway.

**Explain why is cereal is/isn't considered a soup**: It is, because the milk is a cold broth and the actual cereal is the the content. It's just facts.

**Additional information**: (Optional) I'm legitimately black in real life, if that matters. I will share proof with anyone that asks.

**Comment by cottoncandyowo** [comment]
I pardoned your ban and changed it to a 12 hour mute instead. Next time try to refrain from saying since others might think they're allowed to say it too and thats not poggers !!
