### ISSUE TITLE
Ban Appeal: skullyboi10

### ISSUE THREAD

**Issue by skullyboi101** [Kyrobi/Cynagen#188]
**Minecraft username**: skullyboi10

**I was banned on**: ( Dec 28, 2019)

**I was banned by**: Succubi_Snow 
**I was banned for**: Griefing

I was unaware of the rules at the time, or the specifics of them. So I griefed an unclaimed chest full of items. Then proceeded to burn them (this was over the line, I will admit. But life was rough at the time)

**I like to be unbanned because**: It has been quite some time and I have familiarized myself with the rules. At the end of the day, I just want to play with my friends and we have all put so much time into this server

**Explain why is cereal is/isn't considered a soup**: Cause if you think it is, you should be shot. immediately 

**Additional information**: I have a dog

**Comment by Kyrobi** [comment]
Please review the rules here: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you have read it, reply to this post with which rule you think you have broken.
Example: `Hello! I broke Rule #1 Section H`

Once you have replied, your application will further proceed.

**Comment by ToxicSnow** [comment]
Hey its been a minute, as long as you've learned your lesson i have no issue unbanning you.

**Comment by skullyboi101** [comment]
I have learned my lesson. I might shit post every now and then, but it won't be as bad

**Comment by Kyrobi** [comment]
You're unbanned.

**Comment by UnknownMFe** [comment]
But if you do it again tho you will get a perminent ban. 'i think'
