### ISSUE TITLE
Bug: /wild bugged out

### ISSUE THREAD

**Issue by Rallozar** [Kyrobi/Cynagen#189]
**Minecraft username**: Rallozar

**Expected behavior**: The player should be teleported to a random location in the dimension they're in.

**Actual behavior**: The player is teleported to a random location in the Overworld.

**How can this issue be replicated?** This issue can be replicated by typing /wild or /wild:rtp while in the End or Nether.

**Comment by Kyrobi** [comment]
This is now an intended feature
