### ISSUE TITLE
Ban Appeal: I Did Not Grief

### ISSUE THREAD

**Issue by ppietas** [Kyrobi/Cynagen#19]
Please title this post "Ban Appeal:" followed by a name

**Minecraft name**: Pietas

**I was banned on**: 05/07/19

**I was banned by**: Cotton Candy

**I was banned for**: "Griefing"

**A brief summary of what happened before the ban was**: Myself and another person went to someone's base, my friend was looking for inspiration and I was just hopping about for fun. Then, I was looking in their chest, BUT I didn't take anything at all. I was just looking, and all of sudden I was getting killed by three people. So obviously I retaliated and then I was hiding. And I thought it was fun if they could find me, so I debarked a few trees. If THAT is what is considered griefing then I am 100% well and truly willing to replace whatever it was that I debarked. However, I never substantially griefed anything, I was RESPECTFUL. I thought it was legit a fun game of hide and seek, unfortunately, they must not have thought as such.

**I like to be unbanned because**: I did not FULLY grief, and if they are mad about the debarked trees in certain areas, I am more than willing to come back and replace each and every one, as well as planting more for them.

**I often slap little kids because**: I don't because I'm not a sadist.

**Additional information**: I shouldn't have been banned because it was an unsolicited attack against me.

**Comment by cottoncandyowo** [comment]
Aight first off, your friend was had some sort of an attitude towards everyone and also I went to the area you guys were at and you broke a bunch of fences and fucked with Livys stuff. Also, I was told that you were told to leave. I am willing to lift the ban for only 1 more day on you and your friend since it was a first offense though.
