### ISSUE TITLE
Ban Appeal: Hi my Minecraft username is Jaux I was banned on Aug. 4 2020 I was banned by Kyrobi for x-raying I decided to X-ray because I wanted a quick buck cause I wanted to buy 5 more beacons so I could have max potion enchant things so I x-rayed about 12 stacks of diamonds and 12 ancient debris these are in my chests at my base please take them and burn them I want nothing to do with them anymore also I sold some diamonds for about 150 - 200 dollars take the money from me if you can check the exact amount please do I was walking down my x-rayed path mining ancient debris when boom I got banned. I would like to be unbanned because I have had lots of fun on this server during 2017 and 2020 also I love the community and the builds and don't want to lose them forever. cereal isn't a soup because cereal is milk and stuff and soup isn't. Sorry Kyrobi if you don't unban me tell the community I said hi and that I'm sorry.

### ISSUE THREAD

**Issue by Jaux1** [Kyrobi/Cynagen#191]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by Caliteo** [comment]
Hi, please review the rules: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

Once you've read it, please reply with which rule you think you broke. (Ex: rule 2 section b)

Once you've replied we will move forward.

**Comment by Jaux1** [comment]
rule 5 section c

**Comment by Caliteo** [comment]
Please be more mindful in the future, your ban will be reduced to 3 days.

**Comment by Jaux1** [comment]
ok thank you
