### ISSUE TITLE
Ban Appeal: Inflated_Penguin

### ISSUE THREAD

**Issue by InflatedPenguin** [Kyrobi/Cynagen#192]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Inflated_Penguin

**I was banned on**: August 8th 

**I was banned by**: The Server

**I was banned for**: Slurs

**A brief summary of what happened before the ban was**: Naming a name tag something stupid for no reason. What i named it: Mr.PimpleSnootSniggerPants. I didn't realize i accidentally put the n-word in the name.

**I like to be unbanned because**: I really enjoy playing on the server and i was banned because of my stupidity 

**Explain why is cereal is/isn't considered a soup**: Cereal is a soup. 

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Bruh
