### ISSUE TITLE
Player Report: pawciu and aleX_PL

### ISSUE THREAD

**Issue by Jeanbidouille** [Kyrobi/Cynagen#197]
Please title this post: "Player Report:" followed by a name.

Report Template:
####################

**My Minecraft username**:Jeanbidouille

**I am reporting**:pawciu and aleX_PL

**I'm reporting this person for**:Griefing and stealing

**Screenshot or video link if available**:
https://media.discordapp.net/attachments/703233001886318602/749941735660191794/Screen_Shot_2020-08-31_at_8.40.20_pm.png?width=1082&height=677

https://media.discordapp.net/attachments/703233001886318602/749941771055923270/Screen_Shot_2020-08-31_at_8.36.09_pm.png?width=1082&height=677

https://media.discordapp.net/attachments/703233001886318602/749941823161499698/Screen_Shot_2020-08-31_at_8.35.59_pm.png?width=1082&height=677

https://media.discordapp.net/attachments/703233001886318602/749941870561329184/Screen_Shot_2020-08-31_at_8.35.34_pm.png?width=1082&height=677

**Additional information**: (Optional)I have witnesses if needed , also all damages were repaired but they stole things (beacon,gold/iron blocks etc) . They also claimed some of II_Shadow_Cat and some of my builds .

**Comment by Kyrobi** [comment]
Resolved
