### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by ItsVexxed** [Kyrobi/Cynagen#199]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: ItsVexxed/Vexxer232

**I was banned on**: I can't remember.

**I was banned by**: Kyrobi

**I was banned for**: Unclear, gave no reason until I asked. He said "You upset to many people."

**A brief summary of what happened before the ban was**: Well, I wasn't awake. I had just put my main and my alt on to afk on my farms, came back at 10 PM my time to log back on after the restart, and was banned.

**I like to be unbanned because**: I know I was very annoying and rude and to be honest, I wasn't really the best person. I have changed though, and I really regret being such a dick to everyone. I thought that just because they were mean I could be mean right back, I know now that's not even close to true. I spent a year on this server and I enjoyed every bit of it. I spent so much time and money and I just want to come back. I really hope you can all forgive me. It's almost been a year at this point since the ban. I really miss the owo chat, the new players, the funny people and such. I took this server for granted, and when I lost it I was so upset at myself that I had been so mean. I liked to think that you all were the problem to make me feel good about myself, but I was the problem. I really just want to be let back in.

**Explain why is cereal is/isn't considered a soup**: It's a soup because 

**Additional information**: (Optional) yeah

**Comment by JokerBoss99** [comment]
XD
