### ISSUE TITLE
Bug: Glitching Through the ground into either a cave or the void( if in the end)

### ISSUE THREAD

**Issue by ToxicSnow** [Kyrobi/Cynagen#20]
Bug: Glitching Through the ground into either a cave or the void( if in the end)

Succubi_Snow

* Expected behavior**: Being able to run/jump around and explore the world

**Actual behavior**: Randomly triggering the speed anti-cheat and glitching through the ground to the next open space, which sometimes is the void

**How can this issue be replicated: Run/jump around in either a straight line/ in a direction and try to go as fast as you can, the anti-cheat will sometimes act on the player(aka yeeting them through the ground) or doing nothing.

**Additional information**: It's ridiculously random in its nature but its happened not only to myself but a number on people on the server

**Comment by Kyrobi** [comment]
Which check of the anti-cheat does it set off? And is it always that consistent check? (i.e. It's always kill-aura check going off when players falls through the ground)

**Comment by ToxicSnow** [comment]
Its the Speed check, that mainly goes off

**Comment by Kyrobi** [comment]
Now I just need a screenshot

**Comment by Kyrobi** [comment]
Probably fixed.
