### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Aquariuskay19** [Kyrobi/Cynagen#200]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Aquariuskay19

**I was banned on**: (Format: 9 11, 2020)

**I was banned by**: (console )

**I was banned for**: performed  illegal client actions 

**A brief summary of what happened before the ban was**: I was mining obsidian and getting  levels to enchant  then the game lagged and then was banned  

**I like to be unbanned because**: I was on the server for about 3-4 hours mining and making base in a town I don't know what I did wrong I don't think did anything wrong plz  tell what i did 

**Explain why is cereal is/isn't considered a soup**: No it's not soups meal that is  creamy and warm and cereal is less creamy and cold

**Additional information**: (Optional)

**Comment by JokerBoss99** [comment]
unbanned
