### ISSUE TITLE
Ban Appeal: snowyPenguin8910

### ISSUE THREAD

**Issue by snowyPenguin8910** [Kyrobi/Cynagen#201]

**Comment by snowyPenguin8910** [comment]
Ban Appeal: snowyPenguin8910
I was banned on September 13th 2020
I was banned by [Unknown]
I was banned for [unknown]
I like to be unbanned because : I have no clue why i was kicked from the discord server, and it says i can't access the minecraft server because i was banned from the discord server
Cereal isn't a soup because Soup has to be boiled otherwise it is just vegetables and meat floating in water.
Additional Information : Why was I kicked from the discord server???? What did i do wrong???? And why can't i access cynagen????

**Comment by UnknownMFe** [comment]
mmmmm im not sure but it could be a glitch, no admin has responded to this so idk what could happen.
I really hope you get unbanned soon if you didnt do anything wrong...
