### ISSUE TITLE
Ban Appeal: fireboytyler

### ISSUE THREAD

**Issue by 0x1c1ean** [Kyrobi/Cynagen#202]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: fireboytyler

**I was banned on**: september 16, 2020

**I was banned by**: idk

**I was banned for**: being banned from the discord server

**A brief summary of what happened before the ban was**: I was just farming pillagers at a pillager outpost

**I like to be unbanned because**: I did nothing wrong

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)
![image](https://user-images.githubusercontent.com/58238327/93330091-3f9fc800-f7ec-11ea-951b-dd1da2da238c.png)

**Comment by 0x1c1ean** [comment]
umm hello? it's been almost a full week, and nothing has happened; I haven't been unbanned from either platform, and nobody has given me a response, and explained what I have done. Please respond @kyrobi#0633

**Comment by JokerBoss99** [comment]
You’ve been unbanned in-game.
