### ISSUE TITLE
Ban Appeal: BL_Qube

### ISSUE THREAD

**Issue by BlQube** [Kyrobi/Cynagen#203]
BL_Qube:

I was banned on: September 24, 2020

I was banned by: (Succubi_Snow)

I was banned for: Stealing

A brief summary of what happened before the ban was: 
I was helping some people with a raid, went afk for a while and then I was banned.

**I like to be unbanned because**:
I have no idea why I was banned, I wasn't even given a chance to appeal before the ban.

**Comment by ToxicSnow** [comment]
![2020-09-26_03 45 02](https://user-images.githubusercontent.com/44278156/94335642-ee8d9200-ffaa-11ea-8c03-829ba779141d.png)
So you mean that this isnt your username on his beacon that I had to roll back? Oh and also when you get back you are expected to surrender the beacon, iron, gold and the heart of the sea you stole. If you don't, then its changed from a 5 day ban to a perm one.
