### ISSUE TITLE
Ban Appeal: Megaturtell

### ISSUE THREAD

**Issue by Megaturtell** [Kyrobi/Cynagen#204]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
Megaturtell
**I was banned on**: (Format: Dec 23, 2012)
9/28/2020
**I was banned by**: (Leave blank if unknown)
Caliteo
**I was banned for**:
Fly Hacks
**A brief summary of what happened before the ban was**:
Was working on large project with friends, using sponges and sand to remove water
**I like to be unbanned because**:
I wasnt using fly hacks?? My brother was also banned at the same time, assuming it was an internet issue that made it seem that way.
**Explain why is cereal is/isn't considered a soup**:
Soup is hot cereal is cold
**Additional information**: (Optional)
Ive been on this server for over a year i dont hack

**Comment by Caliteo** [comment]
I checked the replay again, I believe I was mistaken. So sorry about this. You're unbanned.
