### ISSUE TITLE
Player Report: Blue_Phoenix23

### ISSUE THREAD

**Issue by ColtCrohnie** [Kyrobi/Cynagen#21]
**My Minecraft username**: ColtCrohnie

**I am reporting**: Blue_Phoenix23

**I'm reporting this person for**: Harrassment, Innapropriate Behaviour

**Screenshot or video link if available**:

**Additional information**: (Optional) After constantly being told not to talk about certain issues (That I will not list) Blue_Phoenix23 still continues the behavior that she has been repeatedly reported, and confronted about. It's gotten so bad that other players are messaging me about the things she says to them and they are all uncomfortable. Please do something about this. Thank you.

**Comment by Kyrobi** [comment]
I think Cotton already has taken cared of this issue. If not, re-open this or make a new post.
