### ISSUE TITLE
Ban Appeal: _ssmokey   i was banned Apr 5, 2020    i was banned for flying    i was banned by kyrobi     i played on the server alot then one day me and my friends were messing around with fly hacks and we made the stupid idea to fly on cynagen, i had never hacked on the server before      cereal is hypothetically solids floating in liquid whereas soup is just liquid therefore cereal is not soup vice versa

### ISSUE THREAD

**Issue by ssmokey** [Kyrobi/Cynagen#215]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by ssmokey** [comment]
im bad i didnt write the ban appeal right

**Comment by ssmokey** [comment]
![obamaspheretra](https://user-images.githubusercontent.com/75945158/102018634-4cd63f80-3d66-11eb-908b-83f399f13925.png)

**Comment by JokerBoss99** [comment]
unbanned
