### ISSUE TITLE
Ban Appeal: lickingfire wednesday 30 december 2020 i was banned for using hacks before the ban i was mining for netherite for arond 30 mins       i would like to be unbanned because i spent hours on the server and love the kind community of the server everybody is so nice unlike lots of servers i have been on in the past i really want to get back to trading and taiking with the locals of the server also grinding for levels i will never hack again i want to be in the community again the reson i hacked in the first place was because i was mining for netherrite for a long time not finding any i was raged and acting childish so i looked up hacks that could get me netherrite fast and decided to use a hack that would mine lots of netherack at once so i could get netherrite fast it was silly of me i should have just grinded for netherrite or traded for it i will nver do it again i swear i already am bored no other servers have the kind players like this one

### ISSUE THREAD

**Issue by lickingfire** [Kyrobi/Cynagen#217]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by lickingfire** [comment]
sorry did this acedentaly

**Comment by lickingfire** [comment]
how will i know if i got unbanned or i will still not ever be allowed on the server?

**Comment by lickingfire** [comment]
i forgot to add this ceral is not soup because milk is just a liquid  and not a soup witch is a mixture of diffrent types if liquids and substances

**Comment by JokerBoss99** [comment]
unbanned
