### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by meltopy** [Kyrobi/Cynagen#219]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:meltopy

**I was banned on**: (jan 06/01/2021

**I was banned by**: (Leave blank if unknown)

**I was banned for**: using a hack client

**A brief summary of what happened before the ban was**:
i broke a tree to test out path hack

**I like to be unbanned because**: i have spent many hours on my base and didnt do anything accept get some leaves

**Explain why is cereal is/isn't considered a soup**:

**Additional information**: (Optional)

**Comment by JokerBoss99** [comment]
unbanned
