### ISSUE TITLE
Player Report

### ISSUE THREAD

**Issue by GriffonDragon** [Kyrobi/Cynagen#22]
Please title this post: "Player Report:" followed by a name.

Report Template:
####################

**My Minecraft Username**:
Blue_Phoenix23 

**I am reporting**:
Succubi_snow 
**I'm reporting this person for**:
Talking with other players about my private life/personal Information
**Screenshot or video link if available**:

**Additional information**: (Optional)
I am Reporting Mod. Succubi_snow for talking to other players about what i talked about in DM's in regards to another player's behavior. I asked if this was against the rules in regards to what happened in the past. I have screen shots, please Dm me as i wish for them to be private at gaudoo#7268

**Comment by Kyrobi** [comment]
I really do think it's a dick move for him to actively talk about you to other people in PM. However, actions are stronger than words. If those people now think that you're bad, then prove them wrong. Everyone talks behind everyone's back, it's the trust of the world. How you handle this situation is more important.

**Comment by ToxicSnow** [comment]
I wasn't talking bad about her in PM, people were messing me about her behavior in PM so I had to be civil and understanding as well as trying to solve the issue before it exploded like it did.
