### ISSUE TITLE
Ban Appeal: RTB344

### ISSUE THREAD

**Issue by RTB344** [Kyrobi/Cynagen#220]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: RTB344

**I was banned on**: 15 jan 2021

**I was banned by**: server

**I was banned for**:Performed illegal client action

**A brief summary of what happened before the ban was**:im just fighting some mobs and i started lagging and got kicked after that when i logged in im banned

**I like to be unbanned because**:i don't use client or any type of aytoclicker or anything no glitches

**Explain why is cereal is/isn't considered a soup**:sry but i dont know what you mean by soup????

**Additional information**: i have a castle that me and my friend building or soo long by mining and getting stuff we dont use any client when i join this server first we started normally playing and died after that we found frostbite who helped us and when i logged in again other day davidplazs my friend give me all the stuff and we started building castle 
![java 2021-01-15 14-18-05-883](https://user-images.githubusercontent.com/77483960/104703607-8ae7ca00-573d-11eb-9a3e-615b2577f5b4.jpg)

**Comment by ToxicSnow** [comment]
[https://youtu.be/OwGNnp8EYp8](url)

Its honestly kinda funny as you mention david, and frostbite, as frostbite was banned for Xray, and lying, and David as you can see in that video was also banned for fly hacks the same as you.

So ya'll won't be getting unbanned as I see no logical reason to allow a group of hackers on to the server.

**Comment by ToxicSnow** [comment]
Hackers get no quarter on this server, there's a reason why the server has lived for as long as it has. and if you watched the video you'd know why, I'm not giving you and your friends a second chance.

**Comment by RTB344** [comment]
aa what video
can i see it

**Comment by ToxicSnow** [comment]
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8
https://youtu.be/OwGNnp8EYp8

**Comment by RTB344** [comment]
ok well i like your security
can you tell me what is the name of the plugin cus if i build a smp i wanna get it
