### ISSUE TITLE
Ban Appeal: Colbyinnit 

### ISSUE THREAD

**Issue by Colbyinnit** [Kyrobi/Cynagen#227]
Ban Appeal: Colbyinnit

**Minecraft username**: Colbyinnit

**I was banned on**: 2021/02/10

**I was banned by**: Succubi_Snow

**I was banned for**: Griefing, Stealing

**A brief summary of what happened before the ban was**: I killed Villagers owned by another person and stole their stuff.

**I like to be unbanned because**: I want to give the things I stole back. Also I feel bad.

**Explain why is cereal is/isn't considered a soup**: because it's not 

**Additional information**: Sorry WoW

**Comment by JokerBoss99** [comment]
Dont do it again
