### ISSUE TITLE
Ban Appeal: isaac

### ISSUE THREAD

**Issue by isaacc100** [Kyrobi/Cynagen#230]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:isaacc100 and my sister's is IHasSmellyFeet

**I was banned on**: (Format: Dec 23, 2012)

**I was banned by**: (Leave blank if unknown)

**I was banned for**: fly hacks??

**A brief summary of what happened before the ban was**: i have no idea

**I like to be unbanned because**: i wasnt online when banned nor did i use fly hacks

**Explain why is cereal is/isn't considered a soup**: it isn't considered soup if you don't crush it and add water

**Additional information**: (Optional)

**Comment by Caliteo** [comment]
Hello, I double checked your replay and the fly hacks are blatant.

**Comment by JokerBoss99** [comment]
Denied
