### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Luis-Houston** [Kyrobi/Cynagen#231]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Luis_Houston

**I was banned on**: March 5th, 2020

**I was banned by**: ColtCrohnie

**I was banned for**: Wrongfully banned for rumors started by Wayward. (Pedo BS)

**A brief summary of what happened before the ban was**: Me and another player were joking around with Caliteo about sending toe pics or something and wayward spread a rumor that I was asking for nudes, everyone believed it and I was banned but it was all cap.

**I like to be unbanned because**: I miss this server, I was wrongfully banned and never given a second chance or a chance to explain myself.

**Explain why is cereal is/isn't considered a soup**: Cereal is not hot.

**Additional information**: (Optional) I've been appealing for a long time, pls give me a second chance.

**Comment by JokerBoss99** [comment]
Unbanned
