### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by MonikoKN** [Kyrobi/Cynagen#232]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: MonikaKN

**I was banned on**: (Format: Oct 31, 2020)

**I was banned by**: (Leave blank if unknown)

**I was banned for**: Inappropriate Username

**A brief summary of what happened before the ban was**: Staff and other players got mad at me because my name at that time was very offensive towards a certain culture and at that time I couldn't change my username since it wasn't the 30 day mark.

**I like to be unbanned because**: I now realize that I should not have had my name at that and made it seem like I was attacking a certain ethnicity when my only intentions on that username was to meme around not offend people.

**Explain why is cereal is/isn't considered a soup**: Cereal is not considered a soup unless it is oatmeal. This is because regular cereal is cold, and soup is supposed to be hot, and oatmeal, on the other hand, is hot like soup, so oatmeal is considered a soup with its texture and temperature, while cereal is not. 

**Additional information**: I hope you understand that I will never put that username I had almost 7 months ago, I now realize how immoral and disgusting I was for doing that. I plan on never doing that again and I now have grown to the realization that no person in the right mind should have done that. I deeply apologize from the bottom of my heart. 

![Banned](https://user-images.githubusercontent.com/84132757/118123392-6e893080-b3b1-11eb-9d61-eb657cd7e184.PNG)

**Comment by JokerBoss99** [comment]
Unbanned, thank you for your honesty.
