### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by cstowe22** [Kyrobi/Cynagen#236]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
cstowe
**I was banned on**: (Format: Dec 23, 2012)
1-23-2021
**I was banned by**: (Leave blank if unknown)
Caliteo
**I was banned for**:
I some toxic thing i said
**A brief summary of what happened before the ban was**:
I dont really remember to be honest
**I like to be unbanned because**:
My friend wants me to get back on the server to play
**Explain why is cereal is/isn't considered a soup**:
because it is cereal
**Additional information**: (Optional)
I was banned a really long time ago and i would just like to be able to play again.

**Comment by HyperfireRS** [comment]
denied

**Comment by cstowe22** [comment]
Why

**Comment by HyperfireRS** [comment]
cringe thing is im not even staff and you beleived me
