### ISSUE TITLE
Ban Appeal: Kyrobi

### ISSUE THREAD

**Issue by EmperorJap** [Kyrobi/Cynagen#24]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
EmperorJap
**I was banned on**: (date)
5/15/2019
**I was banned by**: (Leave blank if unknown)
Servers
**I was banned for**:
"Slurs"
**A brief summary of what happened before the ban was**:
My friend messaged me sup, and then I said hey whats up my dude and then server banned me
**I like to be unbanned because**:
I like the server and I've been working hard
**I often slap little kids because**:
yeet
**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
I don't think the server would ban you for saying "whats up my dude", please try again.

**Comment by ToxicSnow** [comment]
Yeah I'm sorry but I doubt that the server banned you for that And I know what you said to get banned so how about being honest.
