### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Aidenlee0678578** [Kyrobi/Cynagen#243]
Ban Appeal:Aidenlee0678578

**Minecraft username:Aidenlee0678578

**I was banned for:my cousin saying nigg im not gay btw his acc was shotgungang 21

**A brief summary of what happen before ban:shotgungang 21/my cousin was taking to the lockser and oktead about a enchantment table that we wanted we were going to trade for it then they started saying we were gay over and over again so i guess shotgungang got mad at them and said nigg im not gay 
**Why is what you got banned for bad?**:it is bad bc you dont call people niggs and btw i dont know why i got banned for this

**I like to be unbanned because**:bc the server is fun and i did nothing wrong it was shotgungang 21

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:stop shotgungang from calling people niggs and stop him from talking to people like that 

**Explain why is cereal is/isn't considered a soup**:bc you eat cereal with milk and soup has meat and vegetables in it

**Additional information**: please unban me it was shotgungang`s fault and i will be good

**Comment by Kyrobi** [comment]
I have unbanned __SHOTGUNGANG_21. Please refrain from saying such stupid things in chat next time
