### ISSUE TITLE
Ban Appeal:LiamHoag

### ISSUE THREAD

**Issue by LiamHoag** [Kyrobi/Cynagen#245]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:LiamHoag

**I was banned for**:  joking saying i had the  aristotle hack with ally 

**A brief summary of what happened before the ban was**:  a mod asked what client i had and i said aristotle  

**Why is what you got banned for bad?**:saying i had the aristotle hack to the mod    

**I like to be unbanned because**:  because i want to be forgiven    

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:  stop joking in incriminating way 

**Explain why and when the best time to mow the lawn is**: at nighttime because im only up from 6pm to 6am because its too hot outside in texas to be up in daytime doing stuff outside

**Additional information**:  i was initially banned for 7 days and after that screen on the video it did not have the main screen of the hacked client i was joking about having 

![main menu](https://user-images.githubusercontent.com/110272220/181935873-4a16175d-37e1-4951-951e-a3d9bd788928.jpg)
![unnamed](https://user-images.githubusercontent.com/110272220/181935896-6cf43ff8-8905-4f15-b86c-353b99321329.jpg)

https://user-images.githubusercontent.com/110272220/181936026-87aa7d48-4041-45e1-8461-2aaa4279c03d.MOV

**Comment by Kyrobi** [comment]
You have been unbanned
