### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by bloopgits** [Kyrobi/Cynagen#246]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:bloopgaming

**I was banned for**:cheating

**A brief summary of what happened before the ban was**:i was flying

**Why is what you got banned for bad?**:i used hax

**I like to be unbanned because**:the server is fun

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:no use hax

**Explain why and when the best time to mow the lawn is**:the best time to mow the lawn is 1:00am cause its dark

**Additional information**: (Optional)optinal

**Comment by Kyrobi** [comment]
I don't exactly know how you can conclude if the server is fun or not since you started hacking 2 minutes later upon joining the server and have a total of 4 minutes of playtime. You'll have to wait out your ban.
