### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by OkYesIk** [Kyrobi/Cynagen#248]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:
StVexx
**I was banned for**:
Saying a racial slur.
**A brief summary of what happened before the ban was**:
someone said to for someone to yell out racial slurs and i thought it was directed at me, so i said the N word.
**Why is what you got banned for bad?**:
Its racist and hateful.
**I like to be unbanned because**:
I like playing on this server.
**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:
First, I said a racial slur, in my eyes I thought it was a joke but in reality it was hurtful toward the black community.
**Explain why and when the best time to mow the lawn is**:
I think mid-morning would be the best time to mow the lawn because, usually when a citizen mows the lawn at this hour, some are awake and some are not, meaning that this would be the good alarm clock if you are still not awake by now.
**Additional information**: (Optional)
Please don't make fun of me.

**Comment by Kyrobi** [comment]
Ubanned. Please don't make such goof next time
