### ISSUE TITLE
Ban Appeal: Spathus

### ISSUE THREAD

**Issue by Spathus** [Kyrobi/Cynagen#249]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: Spathus

**I was banned for**: Hacking

**A brief summary of what happened before the ban was**: So basically, my brother (ChlorineAsian) asked me to test how good the anticheat is on the server. I asked him why he couldn't just do it, but he said he was too busy making a farm. So I just decided to might as well do something for him and the moment I logged on with the hacks, the anticheat caught me. My brother assured me that even though people were saying L in chat nothing was to be of worry. So I immediate logged and switched to vanilla MC and continued on without a care in the world for another 1-2 hours. Then when I joined today, I saw the ban and reason.

**Why is what you got banned for bad?**: Hacking truly is an "unfair advantage" as some hacks allow you to advance within the game to an extreme extent beyond any human player. It also allows pvp to be extremely one sided.

**I like to be unbanned because**: I did not mean any malevolent intent by hacking, I was just doing something for my brother. 

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: Next time, I will tell him that hacking in general is wrong and that there is no point in hacking, just play the game how it was intended and in turn have more fun.

**Explain why and when the best time to mow the lawn is**: The morning is easily the best time to mow the lawn, because where I live temperatures are always high. Therefore, any reprieve from the heat is welcome.

**Additional information**: (Optional)

**Comment by AnotherRevenant** [comment]
your ban was already reduced by over half. feel like that's worth noting. standard is 7 days
