### ISSUE TITLE
Bug: update supression

### ISSUE THREAD

**Issue by Nightawkdude** [Kyrobi/Cynagen#25]
**Nighthawk**:

* Observers detect updates**:

**Water and observers don't detect updates all the time**:

**It seems to be lag related but water will act funky and flying machines will break every so often. You can see this best at the skull farm**

* A screenshot / video link if available**:

**I don't know what is the exact reason it is missing updates but I think that the game is ignoring some updates because it has to many to process**:

**Comment by Kyrobi** [comment]
I think this issue is also fixed, not sure though. Open this issue back up if it's not fixed.
