### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by TimeKid21** [Kyrobi/Cynagen#250]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: __FuriousBox21

**I was banned for**: cheating

**A brief summary of what happened before the ban was**: was collecting azalea leaves for future projects, i think because of lag i was standing on one of the azalea leaves that i have already sheared but on my screen it looks like the leaf i was standing is still there while probably on some players it looks like im floating. 

**Why is what you got banned for bad?**: i don't know, never cheated on servers and this is the first server i have joined in Minecraft. cheating while it's good, i don't like using it on a game like Minecraft because there's already creative mode anyway where you can do anything in your world

**I like to be unbanned because**: i still have things to do in the villager hall, which btw some villagers still despawning despite 2 blocks apart. same with my base, have been abandoned for like a week. also i like the server and the commands added in, it's neat. same with the claiming, means no griefing and the store is nice for getting stuff that normally you won't get early game.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: probably don't stand on a leaf while collecting it despite looking like it's still there and also probably just get a better wifi lmao

**Explain why and when the best time to mow the lawn is**: mowing where your front is road sounds fun and mowing 8 am sounds good, idk never had a lawn

**Additional information**: (Optional)
never used any cheats while i was there and if i did have cheats on then my phone will probably lag like hell and never play again

**Comment by Kyrobi** [comment]
Unbanned
