### ISSUE TITLE
Ban Appeal: ChlorineAsian

### ISSUE THREAD

**Issue by ChlorineAsian** [Kyrobi/Cynagen#251]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: ChlorineAsian

**I was banned for**: cheating

**A brief summary of what happened before the ban was**: I was looking for a dungeon for an xp farm.

**Why is what you got banned for bad?**: I wasn't actually cheating. I was using an F3 trick I saw my favorite Youtuber Dream use on stream to find structures. It works for bastions, nether fortresses, dungeons, and more. Another thing that may have triggered the anti-cheat is that I'm using Lunar Client. I'm sorry if some of the mods in the client aren't allowed and I'll stop using them. 

**I like to be unbanned because**: Summer break ends in 2 days and I want to spend the rest of it having fun with my friend on Minecraft. I have not done anything else wrong on the server.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: I will stop using Lunar client mods and I'll ask my Mom to unblock the vanilla client for me to use because it is blocked by parental controls.

**Explain why and when the best time to mow the lawn is**: I live in Arizona. Grass doesn't exist here.

**Additional information**: (Optional) Please? I promise I'll stop.

**Comment by Kyrobi** [comment]
If you want to be unbanned, please tell the truth next time. This is clearly x-ray
![image](https://user-images.githubusercontent.com/20980266/182471774-598a260b-8de1-42e4-ad15-81e9bc72dd57.png)

Anyways, your appeal is denied.
