### ISSUE TITLE
Ban Appeal: __ParJoe44

### ISSUE THREAD

**Issue by jrprice44** [Kyrobi/Cynagen#253]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: __ParJoe44

**I was banned for**: Hacking?

**A brief summary of what happened before the ban was**: I was mining at y30 and it popped up in chat that I was hacking.

**Why is what you got banned for bad?**: I wasn't hacking. I was just playing the game.

**I like to be unbanned because**: Since I joined I have been active and voting for this server twice a day.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: I didn't do anything wrong at all. I'm not sure what happened and why I got banned. Someone in chat said I had hack toggled on. ???? I don't even know how to do that.

**Explain why and when the best time to mow the lawn is**: In the evening when it is cool. Not after it rains.

**Additional information**: (Optional) I have know Idea what happened. Chat said I had Hacks toggled on. If I toggled them on it was out of ignorance and I do not even know how to do all of that stuff. I was just mining, I'm not sure what happened.

**Comment by Kyrobi** [comment]
I looked at the replay and it does indeed seem like a false ban. You've been unbanned
