### ISSUE TITLE
Ban Appeal: Gallactick

### ISSUE THREAD

**Issue by Gallactick** [Kyrobi/Cynagen#254]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Username": Gallactick

**I was banned for**: Ban evasion X2

**A brief summary of what happened before the ban was**: I was making a joke about being someone's alternate alternate account

**Why is what you got banned for bad?**: Because he was supposed to be banned ig

**I like to be unbanned because**: I wanna play on the server and don't wanna wait 90 days

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: Not do that and play the game

**Explain why and when the best time to mow the lawn is**: 3:00 am because most people will be asleep by then

**Additional information**: (Optional)

**Comment by AnotherRevenant** [comment]
you're unbanned. kindly refrain from doing that again
