### ISSUE TITLE
Ban Appeal: WTF?!

### ISSUE THREAD

**Issue by B4sh3rk77** [Kyrobi/Cynagen#255]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: BasherK7

**I was banned for**: "Cheating"

**A brief summary of what happened before the ban was**: I was afk and just watching somthing on my other screen, then i got respawned, i look over and everyone is mad at me because someone put alot of items into my inventory, Before this when i was basing with a friend. he gave me items because i asked. this is possibly why.

**Why is what you got banned for bad?**: Idk, i didnt really do anything but be afk. Legit no idea.

**I like to be unbanned because**: I was not cheating. And i have no idea why i was banned for being falsly accused.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: Try not to be afk as much, it would help me explain FASTER WITHOUT GETTING BANNED THE SAME SECOND IM EXPLAINING, JESUS WE CANT EXPLAIN WITHOUT GETTING BANNED THE SAME SECOND.

**Explain why and when the best time to mow the lawn is**: 1 O clock on a sunday. because its a ver gud time.

**Additional information**: I wanna be called tomato.

**Comment by Kyrobi** [comment]
Hello. Judging from the replay of your actions before you got banned, I have reason to believe that you were indeed cheating. You will have to wait until your ban expires.
