### ISSUE TITLE
Ban Appeal: __Boparai_62

### ISSUE THREAD

**Issue by BoparaiAs** [Kyrobi/Cynagen#258]
__Boparai_62
The reason i was banned for was "Ban Évasion"
(According to Indian time)At around 11:30 P.M. , I was building a  shop in the market in a plot which was of 512$. Lord_Fen helped me to get that plot because I was new and didn't know much about the market. Then I left at around 11:45 P.M.
The next day (today) on 25 September,2022 (Indian time) when I logged in to the server after voting for the server , it told me that I was permanently banned from the server and the reason was Ban Évasion.I only have one Id for Minecraft that is __Boparai_62 and I don't know how I could do a Ban Évasion.
I don't know how I broke the rules that I was banned but I request to give me another chance,I will never break the rules again and I will become a honest player.
I will improve myself and help other players also. But please unban me. I am still confused that why was I suddenly banned from Cynagen. According to me I hadn't done anything wrong. But if I broke any rule or did something wrong I wasn't aware about that. Even so apologize for any kind of act that was done by me that is illegal on the server. But I beg you to unban me because this server was the reason I started playing Minecraft again after 3 months even in my exams.
I don't want to lose all the progress I made on the server. I don't know that if I come back again on the server my claims and base would remain the same as it was before. But I request you a million times that please unban me🥺🥺🥺. 
- __ Boparai_62

**Comment by Kyrobi** [comment]
Hello. I've reduced your ban. Please stop messing with other players and mass claiming their land.
