### ISSUE TITLE
Bug: McMMO is Broken

### ISSUE THREAD

**Issue by ColtCrohnie** [Kyrobi/Cynagen#26]
Please title this post: "Bug:" followed by a name.

**Minecraft username**: ColtCrohnie

* Expected behavior**:  Earning McMMO XP, using McMMO Skills, and using McMMO commands.

**Actual behavior**: Commands and skills for McMMO aren't working.

**How can this issue be replicated?** Attempting to type a command from mcmmo like /stats or trying to increase skills.

* A screenshot / video link if available**: 
![image](https://user-images.githubusercontent.com/50608164/58439657-c7633f80-809a-11e9-864f-296a2be6b08c.png)

**Additional information**:

**Comment by Kyrobi** [comment]
Has been fixed.
