### ISSUE TITLE
Ban Appeal: The_Mushi

### ISSUE THREAD

**Issue by DatAxolotl** [Kyrobi/Cynagen#260]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:The_Mushi

**I was banned for**:Cheating - Dont know

**A brief summary of what happened before the ban was**: I left the game for an hour or 2, Then came back and was banned for cheating

**Why is what you got banned for bad?**:Cheating is very bad cause it harms others, I did not do anything though so-

**I like to be unbanned because**:I did nothing wrong and I really enjoy the server.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: I don't know what I did.

**Explain why and when the best time to mow the lawn is**: 3:00 AM

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
You were banned for using xray.
