### ISSUE TITLE
Ban Appeal: ojmaster

### ISSUE THREAD

**Issue by ojmaster** [Kyrobi/Cynagen#261]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft Username**:
ojmaster
**I was banned for**:
cheating? I really don't know how I was cheating, my client crashed and suddenly when I opened Minecraft back up I was banned for cheating, very confused.
**A brief summary of what happened before the ban**:
 I mined for some coal, made a bed, claimed some land then I tried to do the /claim command not realizing it was disabled then my game crashed.
**Why is what you got banned for bad?**:
 I didn't cheat :(
**I like to be unbanned because **:
I was really enjoying just being in a small survival server, while I don't actively talk much I just enjoy having other ppl in the server
**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:
 I didn't cheat :( I promise
**Explain why and when the best time to mow the lawn is**:
When I am not dying in 100+ degree heat
**Additional information**: (Optional)
is it cuz I'm using forge, with optifine and like a mod to add more animations to the game? idk what would've gotten me banned

**Comment by Kyrobi** [comment]
You were using Baritone
