### ISSUE TITLE
Ban Appeal: So i was just crafing loot to build my castle and i got banned idk why so maybe i ot banned for stealing but i didnt saw on rules its not allowed stealing so idk . My user is __Kindforppl3 im new on this server and whst ever bad thing i did pls tell me i will not repeat!!

### ISSUE THREAD

**Issue by Kindforppl3** [Kyrobi/Cynagen#262]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**__Kindforppl3**:

**I was banned for *cheating* **:

**A brief summary of what happened before the ban was i was just crafting and grinding for my new house **:

**Why is what you got banned for bad?**: idk I just got banned I just stole some stuff but stealing wasn't on rules!

**I like to be unbanned because**: I will not repeat the mess I must have done ! Just tell me down below what I did!

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:If stealing isn't allowed I will not steal but idk I didn't saw stealing from rules!Plus everything bad I must've done I will never do!!

**Explain why and when the best time to mow the lawn is**:I dont understand what's this

**Additional information**: (Optional) I don't understand what's this

**Comment by Kyrobi** [comment]
I've reduced you ban to 1 day. Please read up on the rules again. Stealing is considered griefing.

**Comment by JokerBoss99** [comment]
> I got banned permanently for hating ga*
> […](#)

Damn that’s crazy maybe you shouldn’t send STAFF members homophobic shit 😭
