### ISSUE TITLE
X-ray texture pack ban appeal, please remove or shorten this ban, details below or inside the appeal.

### ISSUE THREAD

**Issue by realredpro** [Kyrobi/Cynagen#263]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: realredpro

**I was banned for**: x-ray

**A brief summary of what happened before the ban was**: I was using an x-ray texture pack to find diamonds a total of 23, and all were taken away according to a moderator at the time. (I forgot the name).

**Why is what you got banned for bad?**: Because it broke the rules under cheating, "Using modifications to the game such as x-ray texture packs is also considered cheating.". But I had just joined a few days ago and hadn't read the read the rules at the time of the ban and before.

**I like to be unbanned because**: , I didn't know I was breaking the rules, I was just testing, the x-ray materials have already been taken away so therefore I have gained nothing from it, I have read the rules and won't do it again.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: Stop using an x-ray texture pack inside of Cynagen.

**Explain why and when the best time to mow the lawn is**: 1pm because it is after lunch and you have lots of energy.

**Additional information**: (Optional) Can an admin respond as soon as possible, great thanks.

**Comment by realredpro** [comment]
also, if you dont its fine, i kinda just wanna play the server, i didnt know it was cheating in this server, i have only played like hive and that

**Comment by realredpro** [comment]
idk where to find the rules apart from inside the game, if you unban me or tell me where to find one, i will read the rules

**Comment by realredpro** [comment]
pls reply, ill just play hive whilst im waiting

**Comment by JokerBoss99** [comment]
It’s been 11 minutes since you posted the ban appeal my dude

**Comment by realredpro** [comment]
ik, and

**Comment by realredpro** [comment]
also i lied, hive was the first server i played, but like cynagen is the first survival server ive played

**Comment by r44lly** [comment]
Please stop spamming your minecraft server life in the comments since we get notified of every single one. When possible, an admin will resolve your issue. So please be patient.

**Comment by JokerBoss99** [comment]
Here’s the rules: https://github.com/Kyrobi/Cynagen/blob/master/Information/Rules.md

Also please re-do this question with a good answer **_Why is what you got banned for bad?:_**

**Comment by realredpro** [comment]
ok and ok

**Comment by realredpro** [comment]
alr i read the rules, and sorry about MeteoricChain18

**Comment by realredpro** [comment]
wait, how to change one of the questions

**Comment by realredpro** [comment]
oh yeah sorry about the amount of comments, after this one, all comments will be neccesary

**Comment by realredpro** [comment]
All grammar and unclear responses were edited, this is in response to JokerBoss99 "Also please re-do this question with a good answer Why is what you got banned for bad?:".

**Comment by realredpro** [comment]
> "Please stop spamming your minecraft server life in the comments since we get notified of every single one. When possible, an admin will resolve your issue. So please be patient.". On average how long will I be waiting.

**Comment by JokerBoss99** [comment]
Yeah no, found out that you and your friend threatened to send bombs through the mail XD? No thanks, appreciate the appeal though! You do not have to open another one!
