### ISSUE TITLE
Ban appeal has been resolved.

### ISSUE THREAD

**Issue by realredpro** [Kyrobi/Cynagen#265]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:realredpro

**I was banned for**:X-ray and my ban was raised for no apparent reason.

**A brief summary of what happened before the ban was**:I was mining for diamonds using x-ray and got banned, I hadn't read the rules before so I didn't know it was cheating, and I also put a ban appeal about it and got my ban raised without any communication as to why.

**Why is what you got banned for bad?**:X-ray is considered cheating which I didn't know at the time, and I don't know why making a ban appeal is bad seeing as I have read all the rules and it comes up no where.

**I like to be unbanned because**:My ban was raised unfairly and I didn't know x-ray was cheating at the time.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:Stop using x-ray, but I don't know how to improve my ban appeal.

**Explain why and when the best time to mow the lawn is**:1pm because it is after lunch.

**Additional information**: (Optional)My ban raise was unfair, I was polite (which includes the appeal and the comments) and when asked not too comment that much I only commented on necessary things like responding to other comments.

**Comment by realredpro** [comment]
This was an unfair ban raise.

**Comment by Kiiniko** [comment]
You had contacted your friend about sending bombs through the mail and that same friend had repeated what you said in the server chat.

**Comment by realredpro** [comment]
Okay, fair enough, thanks for letting me know.

**Comment by Kiiniko** [comment]
Now please stop spamming comments on appeals & opening more appeals.

**Comment by realredpro** [comment]
Ok sorry about that, I will wait until the ban is finished, I was only joking and I will not be saying any more, Have a good day.
