### ISSUE TITLE
Ban Appeal: hello i am __Suuuuuujiii please unban me my username** __Suuuuuujiii **. I was bannded for not being a very good person. I am only taking in chat then Console bannded me .  Cause i am taking sommeee of the rubbish things that's why bannded bad. **You like to unban me because I will improve me very much i impoved me and i be the very good person in smp when you unban me :)** I talked rubbish in chat that's the thing I did wrong. The things I do to improve myself is i will be a very good person and always help othe peopls and and gonna always support the best smp cyNagen. **I don't know what the requirements in last one  

### ISSUE THREAD

**Issue by Shubhampla** [Kyrobi/Cynagen#268]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:

**I was banned for**:

**A brief summary of what happened before the ban was**:

**Why is what you got banned for bad?**:

**I like to be unbanned because**:

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:

**Explain why and when the best time to mow the lawn is**:

**Additional information**: (Optional)

**Comment by Shubhampla** [comment]
Please unban me fast i want to play in the best smp @Kyrobi :( please

**Comment by Shubhampla** [comment]
@Kyrobi @joshuag1000 @JokerBoss99 @cottoncandyowo

**Comment by Shubhampla** [comment]
@Kyrobi please check my appeal and unban me i am wating from a long time

**Comment by joshuag1000** [comment]
First IDK why you pinged me i have no power.
Second you actually have to fill out the ban appeal to stand a chance of being unbanned,
Thirdly i dont see much of a chance of you being unbanned with your history: (https://site.cynagen.xyz/bans/history.php?uuid=0000000000000000000901f874270f4d)

**Comment by Shubhampla** [comment]
Sorry bro

**Comment by JokerBoss99** [comment]
Waiting for 4 hours is not a long time, especially when it’s a weekday and you made your appeal very early in the morning. Anyways, in less than 2 months you were punished for more than 7 different things/rules broken. We gave you the benefit of the doubt time and time again, but you still went out of your way to do things against the rules :/ 
How have you improved yourself in the past month that we should expect you to not constantly break the rules?

**Comment by Kyrobi** [comment]
Make another appeal when it's Christmas. It will be your Christmas gift

**Comment by Shubhampla** [comment]
Thank you, I will do that.
