### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by GlaticHero** [Kyrobi/Cynagen#270]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

glatichero

**I was banned for xraying

**A brief summary of what happened before the ban was i was in the nether with one of my friends looking for a fortress

**Why is what you got banned for bad i got banned for using xray like twice in my life 

**I like to be unbanned because because i will delete xray and wont cheat again

**Reflect on what you did wrong. What are some things you will start doing to improve yourself? i will nolonger cheat/use xray in games anymore and i will start all over

**Explain why and when the best time to mow the lawn is**: afternoon thats when the sun is out and it wont be so hot depeneding where you live and ye

**Additional information**: (Optional)

**Comment by JokerBoss99** [comment]
Ban reduced to 3 days.
