### ISSUE TITLE
Ban Appeal: __SrgPayne935529

### ISSUE THREAD

**Issue by SrgPayne935529** [Kyrobi/Cynagen#272]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: __SrgPayne935529

**I was banned for**: Xraying

**A brief summary of what happened before the ban was**: I was offline so idk

**Why is what you got banned for bad?**: I had something that was not allowed

**I like to be unbanned because**: Because I am playing with a group of friends

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: I have learned from my mistakes and wont do it again, already deleted it.

**Explain why and when the best time to mow the lawn is**: When: On a Friday or Saturday usually around 11am-3pm. Why: Sun is out most likely a nice breeze and mostly just a reasonable time to do it

**Additional information**: (Optional) I sorry

**Comment by Kyrobi** [comment]
You're unbanned
