### ISSUE TITLE
Ban Appeal: mooperman32

### ISSUE THREAD

**Issue by mooperman** [Kyrobi/Cynagen#276]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: mooperman32

**I was banned for**: cheating 

**A brief summary of what happened before the ban was**: I was playing pop with my friend and using my trident to fly around

**Why is what you got banned for bad?**:
I wasn't cheating and I think it made some kind of mistake 

**I like to be unbanned because**: I am innocent and was just playing like normal 

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:
I didn't do anything

**Explain why and when the best time to mow the lawn is**: around 1 pm this allows you to make sure you aren't waking up your neighbors and allows the morning dew to dry

**Additional information**: (Optional) I think the server thought I was flying idk but pls unban me

**Comment by Kyrobi** [comment]
You've been unbanned
