### ISSUE TITLE
Bug: Elytra unable to fly long distances

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#28]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post: "Bug:" followed by a name.

**Minecraft username**: JokerBoss99

* Expected behavior**: Able to fly until I run out of momentum 

**Actual behavior**: Get lagged back all the time, no matter what kind of takeoff style I try.

**How can this issue be replicated?**: Fly around with an elytra for an extended period of time (more than 5 seconds)

* A screenshot / video link if available**: https://youtu.be/uohaBFQGDro

**Additional information**: I initially thought that it was just for 1.14, but then I switched to 1.13 as you can see in the video, and it still doesn't work. I asked in chat if anyone else was having the same problem, but nobody responded so I'm coming here to hopefully shine some light on it and get some testing done.

**Comment by Kyrobi** [comment]
Fixed.
