### ISSUE TITLE
Ban Appeal:__Boparai_62 

### ISSUE THREAD

**Issue by Amritbeer** [Kyrobi/Cynagen#283]
**Minecraft username**:__Boparai_62 

**I was banned for**:Cheating

**A brief summary of what happened before the ban was**:I was just clearing up some land around my base to build a new house there.

**Why is what you got banned for bad?**:I didn't get what to write in this section

**I like to be unbanned because**:Of all other servers I like cynagen the most. I like this server very much and the players too are very good. I have made great progress on this server and I don't want my progress to be lost

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:I really don't know why I was banned because according to me hadn't done anything wrong like cheating. I am a honest player and I will improve myself and I will not do anything bad on the server.

**Explain why and when the best time to mow the lawn is**:please unban me as early as you can because I don't won't my base to be looted by any other player. So I request you to unban me within 1 or 2 days(please).

**Additional information**: please unban me and I request you to tell me the actual reason that why I was banned.I hope you listen to my request.

**Comment by Kyrobi** [comment]
I have confirmed it was indeed a false ban. You've been unbanned
