### ISSUE TITLE
Ban Appeal: _Trinex

### ISSUE THREAD

**Issue by Trinex64** [Kyrobi/Cynagen#286]
**Minecraft username**: _Trinex

**I was banned for**: cheating

**A brief summary of what happened before the ban was**: I was building a tree farm, had some mods to make it easier and also accidentally pressed a hotkey for a very fast autoclicker

**Why is what you got banned for bad?**: I wasn't cheating, the server just thought I was

**I like to be unbanned because**: I had mods that I use for making redstone contraptions, not any cheats

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: The mods options were pretty sus as they are mainly for making it easier to build redstone contraptions in singleplayer worlds, this includes stuff like autoclickers, changing block rotations and block offsets (these i had disabled). I was also using easy place from litematica so i could place the blocks on the schmatic easier, the schematic is all visual but the easy place made it so it would basically place the blocks mid air where they should be. When Mod's asked me to stop, I did. Anyways moral of the story, if the mod is sus for servers, it will get you banned sooner or later, even if you're not hacking and you're intentions are just not bad.

**Explain why and when the best time to mow the lawn is**: On a hot summer day, not too hot as that'd be a pain, but hot enough to enjoy some lemoade

**Additional information**: ily <3 (no homo)

**Comment by Kiiniko** [comment]
wouldnt this have been avoided if you had just taken the mods out of the folder when we asked you to turn them off

**Comment by Kiiniko** [comment]
i'd suggest taking all of those out of the folder before getting unbanned ._.

**Comment by Trinex64** [comment]
is it possible that i could keep the schematic mod? i have stuff from there disabled, its only the schematics i need tbh.
the schematics are just visual ghost blocks so i dont think the anti-cheat would pick something like that up.

**Comment by Kiiniko** [comment]
the schematic is fine. anything that "plays" the game for you, remove it

**Comment by Trinex64** [comment]
alright, i already did.

**Comment by Kiiniko** [comment]
okay ill unban in a second. another instance of this, im leaving it tho
