### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Klazity** [Kyrobi/Cynagen#288]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:
KlazityYT
**I was banned for**:
Aggressive towards players and staff 
**A brief summary of what happened before the ban was**:
i have the whole thing recored, i was banned cause i was arguing casue of 
**Why is what you got banned for bad?**:
 i didnt do it
**I like to be unbanned because**:
 i need a court trail immediityly
**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:
 nothing defending myself 
**Gives 5 reaons why it is justified to steal from a poor elderly person**:
1. robbing old people
2. they didnt have netherite armor
3. big money
4. free target
5. bad + ez score
**Additional information**: (Optional)
 
i need to have court trail iimmeditly it will be held in dicord or server i have all the proof i have a lot as well

**Comment by Klazity** [comment]
i nned court i false banned
 i have proof

**Comment by allyxc** [comment]
rightfully banned

**Comment by Klazity** [comment]
> rightfully banned

still, havent given me a reason i was defending myself from some asshole who had full netherite armor and was killing someone who was new to the server and kept harrasing me sooooooooo im in the wrong????? explain, you gave me a bs reason when you dont really know the half of it, but okay.

**Comment by allyxc** [comment]
i'm sorry you building your base around puppy & them asking you to leave & you threatening to kill them is not your fault?

**Comment by allyxc** [comment]
you literally had just joined & were already aggressive towards players bro

**Comment by Klazity** [comment]
well no i was building with tony the tiger, he said i could build with him and also still have proof he threatend me first, and killed me first and started all of it, i have proof of all of this.

**Comment by allyxc** [comment]
send me this "proof" ⋆⁺₊ ally ⁺₊⋆#7594
