### ISSUE TITLE
Ban Appeal: 1_1KNAX1_1 i was banned for doxxing so i basicaly said an adress and i wanna be unbanned cuz i just took a radom place on google maps and i know i shouldnt have doe it and it wont happen again i cant draw shit so i cant attach a drawing of a pig balancig an egg

### ISSUE THREAD

**Issue by KNAXPL** [Kyrobi/Cynagen#290]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:

**I was banned for**:

**A brief summary of what happened before the ban was**:

**Why is what you got banned for bad?**:

**I like to be unbanned because**:

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:

**Attach a drawing of a pig balancing an egg on its head.**

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. Any rendition of the drawing will disqualify you immediately from the appeal
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Invalid appeal. Please make another appeal and fill in the information in the correct field
