### ISSUE TITLE
Ban Appeal: __BOPARAI_62 

### ISSUE THREAD

**Issue by Amritbeer** [Kyrobi/Cynagen#291]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:__BOPARAI_62 

**I was banned for**:cheating 
Edit- it's 9 hours since I  made the ban appeal and now the reason is showing,"4 blocks" and I was banned by allyxc. I dont really know what kind of reason this is.

**A brief summary of what happened before the ban was**:I was building a house for myself by watching a tutorial from YouTube and out of nowhere a message came in the chat and it showed that it was sent by me but i didnt even send that message. I dont clearly remember what the message was but I think the message said,"Hello fellas I want you to know that I am using hacks."

**Why is what you got banned for bad?**:I don't know what to write here 

**I like to be unbanned because**:as I have said before that according to me I haven't done anything wrong I don't won't my progress to be lost that I have done on the server. I also want to say that I am a mobile player and I don't really know how to use hacks and its up to you that you believe it or not.

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:I don't want my progress to be lost. I haven't done any kind of cheating like hacking on the server and I promise I will not do any kind of cheating in the future.

**Attach a drawing of a pig balancing an egg on its head.**(https://photos.app.goo.gl/sxtqVCDuy4fsM4RK7)
I don't have a pc so I had to draw it on paper

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. Any rendition of the drawing will disqualify you immediately from the appeal
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

**Additional information**: Kyrobi if you remember a month ago I was banned for the same reason a month before and you told me it was a false ban and I believe that this is also false ban. Please tell me afterwards that what was the real reason behind banning me.
Please unban me as soon as possible

**Comment by Kyrobi** [comment]
Nice drawing of the pig. I have verified that it was a false ban. You have been unbanned.
