### ISSUE TITLE
Ban Appeal: VosanFox

### ISSUE THREAD

**Issue by VosanFox** [Kyrobi/Cynagen#292]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: VosanFox

**I was banned for**: saying the N word cuz i was explaining what someone said

**A brief summary of what happened before the ban was**: i wanted to give an example of what crazy things my classmate does

**Why is what you got banned for bad?**: the N word is racist

**I like to be unbanned because**: Cynagen is a really fun server and i didnt mean to say it in a bad way

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: i will be careful with what i say

**Attach a drawing of a pig balancing an egg on its head.**

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. The drawing can be on paper or digital
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

**Additional information**: (Optional)
![pigballancinganeggonitshead](https://user-images.githubusercontent.com/127143189/223207002-8275ca4f-38e4-4c6a-85de-3d1afab83491.png)

**Comment by Kyrobi** [comment]
Nice pig. Please refrain from saying a slur in chat next time >.>
