### ISSUE TITLE
Ban Appeal: GaloreSloth7489

### ISSUE THREAD

**Issue by Galoresloth** [Kyrobi/Cynagen#293]
![16782851482263502393724149741320](https://user-images.githubusercontent.com/127315211/223736965-a8703c1a-400d-4546-9530-502f6903a66e.jpg)
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:GaloreSloth7489

**I was banned for**:cheating

**A brief summary of what happened before the ban was**:a guy named taha ahmed shah stole my diamond sword and  then out of nowhere i automatically chatted  hey fellas i would like u to know that i got hacks on

**Why is what you got banned for bad?**:it was saying i got banned for cheating but i didnt 

**I like to be unbanned because**:i didnt cheat

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:i didnt cheat 

**Attach a drawing of a pig balancing an egg on its head.**

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. The drawing can be on paper or digital
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

**Additional information**: (Optional)

**Comment by Galoresloth** [comment]
Pls help and ban a guy named taha ahmed shah he stole my diamond sword to

**Comment by Galoresloth** [comment]
-

**Comment by Galoresloth** [comment]
Pls

**Comment by JokerBoss99** [comment]
unbanned, if this happens again please do not spam the appeal with comments. We will see your appeal and get back to you when we are available.
