### ISSUE TITLE
Ban Appeal: __JJgaming073741

### ISSUE THREAD

**Issue by JJgaming073741** [Kyrobi/Cynagen#295]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:__JJgaming073741

**I was banned for**:Cheating

**A brief summary of what happened before the ban was**:I was making a lava moat

**Why is what you got banned for bad?**:Because cheating is unfair

**I like to be unbanned because**:I wasn’t cheating and it was a bug

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: I’ll start doing my 5 a day

**Attach a drawing of a pig balancing an egg on its head.**

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. The drawing can be on paper or digital
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

![](https://cdn.discordapp.com/attachments/1084171158225686610/1084588178792530031/image.png)

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
We have moved our ban appeals from GitHub to Discord. Join https://discord.gg/wgvZRszvc4 instead.
