### ISSUE TITLE
Ban Appeal: El_Gorto

### ISSUE THREAD

**Issue by el-gorto** [Kyrobi/Cynagen#297]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:El_Gorto

**I was banned for**:cheating

**A brief summary of what happened before the ban was**: my game was lagging out and i wasnt hacking

**Why is what you got banned for bad?**:cuz cheating is un fair and bad

**I like to be unbanned because**:because i wasnt actually cheating and it was a bug

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:i will improve my self by eating my 5 a day

**Attach a drawing of a pig balancing an egg on its head.**
![image](https://user-images.githubusercontent.com/127688566/225118567-57a9fbdc-7c2d-41e5-8d57-abb15ee22bbc.png)

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. The drawing can be on paper or digital
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

Here is an example:
![mspaint_Z3YfxnkcA0](https://user-images.githubusercontent.com/20980266/221483354-51b99be3-a087-42d1-94e8-07d164e7848c.png)

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
We have moved our ban appeals from GitHub to Discord. Join https://discord.gg/wgvZRszvc4 instead.
