### ISSUE TITLE
Ban Appeal:  vexxist

### ISSUE THREAD

**Issue by vexxistt** [Kyrobi/Cynagen#298]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**: vexxist

**I was banned for**: being an incredibly annoying goober, terrorizing the player base and being a not great person around everyone

**A brief summary of what happened before the ban was**: i don't really remember anymore, i just know it was entirely my fault and i was being toxic

**Why is what you got banned for bad?**: who would want to be in a community with an individual with no social awareness and breaches boundaries constantly !!

**I like to be unbanned because**: it has been two entire years now, and for the sake of nostalgia i really want to see all of the stuff i made as a younger person. i remember spending a lot of time here and sometimes i look back and think of the things i had made. it would be incredible to be unbanned again, and i know that i logged on with a vpn at one point and was an asshole and was trolling, which was obviously childish and i regret doing it, though. i hope i can be forgiven and be let back in. if it would help, i could be given a permanent mute !!

**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**: i believe that the way i acted was awful, and looking back on how i was three years ago makes me cringe every time, even outside of this server. i have change drastically, i am no longer the same person i was then. i have already worked on myself, i am more mature, i have my life in check, i can almost drive now and i'll be getting a job soon. i hope that my  actions can be forgiven once and for all.

**Attach a drawing of a pig balancing an egg on its head.**
![image](https://user-images.githubusercontent.com/128004576/225478433-3db932f5-fa68-4bee-be86-33393f819569.png)

Please attach a drawing of a pig balancing an egg on its head in your ban appeal.
1. The drawing MUST be done by YOU
2. The drawing can be on paper or digital
3. You need to include your Minecraft username in the bottom right. The name needs to be legible

**Additional information**: (Optional)

i truly hate myself for who i was at that time, i have entirely revamped my entire self, how i act, look, eat. i hope that i can be given a second second second second second chance here. thank you for reading

**Comment by vexxistt** [comment]
i realize i very much misread the drawing prompt, and instead of an egg i drew a lightbulb ! 
![image](https://user-images.githubusercontent.com/128004576/225767827-167280b2-6294-484a-8513-a35c5d850b6a.png)

**Comment by Kyrobi** [comment]
We have moved our ban appeals from GitHub to Discord. Join https://discord.gg/wgvZRszvc4 instead.
