### ISSUE TITLE
Bug: fishing rod undeploys just before fish bites 

### ISSUE THREAD

**Issue by GriffonDragon** [Kyrobi/Cynagen#30]
**Minecraft username**:
Blue_Phoenix23
* Expected behavior**:
Fish bites hook, user pulls fish (or item) out of the water
**Actual behavior**:
Fish will almost get to the hook, when suddenly the rod is no longer deployed
**How can this issue be replicated?**
Start fishing and wait for fish
* A screenshot / video link if available**:

**Additional information**:
The issue doesn't always happen, but it happens enough to be an inconvenience

**Comment by Kyrobi** [comment]
Fixed.
