### ISSUE TITLE
ban appeal: LuckierLime

### ISSUE THREAD

**Issue by LuckierCarrot** [Kyrobi/Cynagen#300]
Hello So i got banned forever ago. And I got banned for inappropiate language and cursing ALOT. As i mentioned that was awhile ago and im not as much of a idiot. Im very sorry for making the server unfriendly and being a idiot and promiss to try to not be a idiot again. I was friends with alot of people on the server and i would like to check it out again and talk on the discord if not thats fine and have a great day (:

**Comment by JokerBoss99** [comment]
Please re-write your appeal so it has the correct format. Also in the appeal you have to promise me that you will behave yourself on the server

**Comment by Kyrobi** [comment]
We have moved our ban appeals from GitHub to Discord. Join https://discord.gg/wgvZRszvc4 instead.

**Comment by LuckierCarrot** [comment]
Alright thanks for letting me know i sent an appeal on the discord and i
promise to behave myself on the server and discord
Love LuckierFurry
