### ISSUE TITLE
Bug: boat kicks me out ?

### ISSUE THREAD

**Issue by rainboweater3e** [Kyrobi/Cynagen#32]
**Minecraft username**: Rainboweater3e

* Expected behavior**: able to ride a boat to get to land or whatever needed

**Actual behavior**: gets in boat and holds W, before i even move i get kicked out of it

**How can this issue be replicated?** get in a boat and try to use it

* A screenshot / video link if available**:

**Additional information**: it was working okay at first but then i just couldn't use it >:( i had to go do something else when i need Squidwards!

**Comment by Kyrobi** [comment]
Hello, this issue should be fixed. Please open another report if this issue still persists.
