### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by CrabAficionado** [Kyrobi/Cynagen#34]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Bano2

**I was banned on**: July 9th 2019

**I was banned by**: "Console"

**I was banned for**: replying "niBBa what?" to something someone else said

**A brief summary of what happened before the ban was**: I asked if someone other than the claim owner was able to trade with villagers on another persons claim, someone else said yes, I said "nice, does anyone want to use my mending villager?", he said "can i kill him?", I replied "niBBa what?" and was banned for 48 hours

**I like to be unbanned because**: I figured it was okay because this server seems pretty meme-y and a bit edgy considering that there are things like signs that say "Fuck" scattered around the world, jokes about "THOTS", and jokes about dead babies being thrown around at random.

**I often slap little kids because**: crabs are far superior to human children

**Additional information**: i have never used github before and may have submitted a blank ban appeal on accident

**Comment by Kyrobi** [comment]
I'm going t assume that this was an honest mistake seeing that this server is mostly edgy. You're unbanned.
