### ISSUE TITLE
Ban Appeal: Squakamole

### ISSUE THREAD

**Issue by Squakamole** [Kyrobi/Cynagen#35]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: 7/10/19

**I was banned by**: Scubbi

**I was banned for**: Stealing

**A brief summary of what happened before the ban was**: I was strip mining for diamonds and then I got banned out of nowhere.

**I like to be unbanned because**: I don't know what I am accused of stealing am curious and if I did take something from someone I didn't do it deliberately and I will gladly pay for whatever I mistakingly took.

**I often slap little kids because**: just because

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
You participated in a hole dig last night. The only thing that was required was to leave all iron mined in a chest near the hole. After everyone else left after finishing the area, you stole the majority of the iron ore and ingots from the chest. After you were confronted, you left the server.

According to the other staff, this isn't the first time that you've stolen from another person. 

If you truly only did it only on accident and that the statements presented are wrong, you may reply to this thread to clear up the unban. For now, your ban of 7 days stays.

**Comment by Squakamole** [comment]
I don't want to accuse anyone of being wrong, but I truly thought that it was a community thing and I didn't intentionally steal the iron and once I get unbanned I will gladly repay anything.
