### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by MrSeven7up** [Kyrobi/Cynagen#36]
This is more a personal problem I think. I'm new in the server and you recently upgrated it to 1.14.3 version, the problem is that I'm not able to run that version because of my pc.
I was wondering If you could add back the 1.13.2 version again.
I hope that I'm not the only player with this problem, as I said I am new and I will like to continue playing.

Greetings and Thank You!

**Comment by ColtCrohnie** [comment]
Unfortunately if we rolled back the update now many things would break, most of the issues will be fixed once Mojang releases 1.14.4 so please be patient

**Comment by JokerBoss99** [comment]
If you are having performance issues with your client itself, I would highly recommend installing optifine ( https://optifine.net/downloads ) and then turning most of the settings down to minimal to boost your client’s performance. Optifine is an allowed mod on the server, and will only help!

**Comment by MrSeven7up** [comment]
Hi! Thanks for the answers.
Fortunately I solved the problem, I changed some options and I can play normally now, Thank You!
