### ISSUE TITLE
Ban Appeal: oebear

### ISSUE THREAD

**Issue by oebear** [Kyrobi/Cynagen#38]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**oebear**:

**I was banned on**: (19.7.13)

**I was banned by**: (jokerboss99)

**I was banned for**:xray

**A brief summary of what happened before the ban was**:he said that if i admit that im xraying then imma get less ban time and i admitted

**I like to be unbanned because**:well i got perm banned so

**I often slap little kids because**:why not >D

**Additional information**: (noup)

**Comment by JokerBoss99** [comment]
Hope you learned your lesson. If you cheat again, you will not have the opportunity to appeal your ban.

**_User tempbanned for 2 days_**
