### ISSUE TITLE
Ban Appeal: blitzAlex

### ISSUE THREAD

**Issue by blitzAlex** [Kyrobi/Cynagen#40]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: blitzAlex

**I was banned on**: (date) 7/25/2019

**I was banned by**: (Leave blank if unknown) ColtCrohnie

**I was banned for**: X-Ray

**A brief summary of what happened before the ban was**: I was working on my new base before being rightfully accused of X-Ray across public chat by Colt and other admins/mods and subsequently banned.

**I like to be unbanned because**: While I regrettably DID X-Ray on the server, it occurred at the very beginning of my time on Cynagen when I didn't think I would continue playing. I fully admit to X-Raying for the first couple days I was on the server, but as I began to meet more people and make more friends, I realized that this was a server I actually cared to devote my time to and stopped X-Raying at once. Alas, the evidence that I created came back to bite my ass weeks later, and here we are. I promise, if granted an appeal, to continue never X-Raying again and to be forever grateful for the mercy shown to me. Please consider this as I highly desire to continue playing with the friends I have made on the server.

**I often slap little kids because**: they tell me that Fortnite is better than Minecraft and to "take the L"

**Additional information**: (Optional) I'm sorry for playing dumb in server chat; I was caught by surprise.

**Comment by ColtCrohnie** [comment]
Okay, so after reading this I think it would be okay to bring you back to the server, however you did break the rules so you do have to be punished in some way. I'll reduce your ban to 7 days on the terms that you remove whatever you use to x-ray, and to be honest with staff from now on. Also when found guilty of breaking the rules a bad way to react is "ban be then" so I would avoid saying that too lol.

**Comment by blitzAlex** [comment]
Ok, thank you. I have already completely removed the client I used to X-Ray, and I apologize for my rude response. I just wanted to get the ban over with so that I could avoid being further roasted by the whole server.
