### ISSUE TITLE
Mods T_T

### ISSUE THREAD

**Issue by LavaLast** [Kyrobi/Cynagen#42]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**LavaLast:

**I was banned on**: (july 27 2019)

**I was banned by**: (CottonCandy_)

**I was banned for**: (using mods)

**A brief summary of what happened before the ban was**: I used a rainbow cross hair and cords on my screen and the admin felt that was a hack and banned me. 

**I like to be unbanned because**: I didnt fly or cheat what so ever. I only used add on's 

**I often slap little kids because**: Word?

**Additional information**: (Optional) Pls un-ban me. Ill stop using them then if it makes u happy

**Comment by Kyrobi** [comment]
"I'll stop using then if it makes u happy" is not a good response after getting banned.

You'll be given another chance as long as you don't use a freaking hacked client just for a crosshair. Use a texture pack instead.
