### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by swiftbananass** [Kyrobi/Cynagen#43]
I have been banned??? For griefing??? I have not griefed yet and I would appreciate if you would unban me before the 24 hours

**Comment by cottoncandyowo** [comment]
Raven TPed me to her nether highway and when I checked who broke the ice it told me that it was you, and it went on for over a few hundred blocks.. I was confused at first because you play the server a lot and it couldn't have been you so I gave you a small 2 day ban since it was first offense..
