### ISSUE TITLE
Ban Appeal:

### ISSUE THREAD

**Issue by BreadKrumbz** [Kyrobi/Cynagen#44]
**Minecraft username**: BakedDough

**I was banned on**: 7/27/19

**I was banned by**: Colt

**I was banned for**: Inappropriate structures 

**A brief summary of what happened before the ban was**: went around and built an inappropriate structure, and got banned for building said structure. Person who banned me said that according to the rules, i'm not allowed to build said structure, but then again, it's not on the rules

**I like to be unbanned because**: No rules were broken

**I often slap little kids because**: Why not

**Additional information**: (Optional) Me, along with 3 other people or so were banned for this, as it was a group effort. It would be nice if they were let go, as they were banned for the same reason.

**Comment by ColtCrohnie** [comment]
When a staff member tells you to stop making inappropriate structures and you continue to do so it’s bannable. Also people have been banned a lot quicker and for a lot longer than you were so I would just wait out your sentence and never try the same thing again.

**Comment by BreadKrumbz** [comment]
Maybe it would be more fair if another staff member to see this through for an unbiased response?

**Comment by ColtCrohnie** [comment]
What would be fair is you listening to staff the first time around

**Comment by BreadKrumbz** [comment]
What would be fair if you didn't ban me for something not on the rules, the very thing your own argument was based on

**Comment by ColtCrohnie** [comment]
I also told you to stop and you didn’t, some of the rules were heavily revamped recently and inappropriate structures just got left out.

**Comment by BreadKrumbz** [comment]
Well, that's not my responsibility to have the rules stamped into my frontal lobe. Nor is said rule available for me to view to begin with

**Comment by ColtCrohnie** [comment]
You’re right, it’s not. Your job is to FOLLOW the rules and listen to staff. You did neither, so you and your friends can wait out your ban

**Comment by BreadKrumbz** [comment]
Right, how about we have ANOTHER staff member who wasn't part of this in order to have an UNBIASED view on the situation, instead of you promoting yourself in the conflict?

**Comment by ColtCrohnie** [comment]
We all speak with the same voice, you’ll get the same answer

**Comment by BreadKrumbz** [comment]
I doubt you are all a hive mind, and share the same brain, thank you.

**Comment by Kyrobi** [comment]
All 4 player's ban has been reduced.

**Comment by BreadKrumbz** [comment]
Thank you
