### ISSUE TITLE
Problem with world generation

### ISSUE THREAD

**Issue by Rainbroooo** [Kyrobi/Cynagen#45]
A part of this end portal got cut off by world generation. It's very frustrating, i've been trying to find this stronghold for a solid hour and a half. I don't know if I can ask an admin to fix that or if we're supposed to just accept that the game messed up. Either way, please update me on discord, thanks !

in game name: \_Rainbro_
discord: Twinkle Sprinkle#2780 

![2019-07-30_14 58 47](https://user-images.githubusercontent.com/53479968/62131676-e4570180-b2db-11e9-8638-d7aef674a14b.png)

**Comment by Kyrobi** [comment]
I will make an attempt to fix it. No guarantees.

In the mean time, claim the area so that no one will destroy the area.
