### ISSUE TITLE
Bug: Concrete powder not evolving into concrete

### ISSUE THREAD

**Issue by aHungiePanda** [Kyrobi/Cynagen#49]
Please title this post: "Bug:" followed by a name.

**Minecraft username**: aHungiePanda

**Expected behavior**: place concrete powder next to water source, here evolution music, see square blink white and black, see text that says "CONCRETE POWDER has evolved into CONCRETE"

**Actual behavior**: places concrete powder next to water source and nothing happens

**How can this issue be replicated?** place concrete powder next to water source and watch paint dry

**A screenshot / video link if available**: nope

**Additional information**: hi Kybie Wybie

**Comment by aHungiePanda** [comment]
actually nevermind after letting the block sit there for 10 minutes it started working again. but still a bug nonetheless.

**Comment by aHungiePanda** [comment]
nevermind i take that back. its just buggy

**Comment by Kyrobi** [comment]
Works fine. It just happens when the server is lagging. Nothing I can do right now.
