### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by OneChromieHomie** [Kyrobi/Cynagen#50]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
OneChromieHomie
**I was banned on**: (date)
7-31-19
**I was banned by**: (Leave blank if unknown)
kyrobi
**I was banned for**:
"hacking"
**A brief summary of what happened before the ban was**:
i was minding my own business, when this guy accuses me of hacking, by walking on water for 5 seconds. i dont know if this was some sort of glitch on his end, but ive been minding my own business, adding to my house, and working on my shop. I have no motive, or any other evidence to prove i was hacking. maybe, i appeared to be flying, because i happen to put cobblestone blocks around the edge of my claims to mark them, and one of them was on water, i dont know
**I like to be unbanned because**:
i put hours into my house, and was just perma banned off some baseless accusation
**I often slap little kids because**:

**Additional information**: (Optional)
look, i know who you are, and I know you arent going to unban me, because you think I was hacking for 5 seconds. i dont care, but i want to make this public

**Comment by cottoncandyowo** [comment]
Hello, you have been unbanned.
