### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by magehunter99** [Kyrobi/Cynagen#52]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: magehunter_99

**I was banned on**: 8/5/2019

**I was banned by**: Server
**I was banned for**: Saying the N word

**A brief summary of what happened before the ban was**: My younger brother whom is 16 thought it would be funny to go on the server and say the N word, as he is just that immature. 

**I like to be unbanned because**: Because I am truly sorry that he did this and I will ensure that he never has access to the account ever again.

**I often slap little kids because**: Because they get me banned from servers.

**Additional information**: I love Cynagen, I'm friend with Ocean_Man7 he can vouch for me

**Comment by JokerBoss99** [comment]
Make sure nothing like this happens again. I will be unbanning you and giving you a temp mute for 24 hours. Please ensure this doesn’t happen again.

**Comment by magehunter99** [comment]
Thank you joker boss 99
