### ISSUE TITLE
Ban Appeal: xXDemonZBloodXx

### ISSUE THREAD

**Issue by demonzblood** [Kyrobi/Cynagen#58]
xXDemonZBloodXx

I was banned on 2019-08-28

I was banned for Being an overall unpleasant person in chat

Just tp requesting some people and somebody accepted and showed me his place and then he just started hitting me but i killed him and then we just started cursing and being toxic in the chat.

I like to be unbanned because it was my mistake and I will listen to the chat rules before i send anything in the chat.

I often slap little kids for fun as a hobby.

Additional Information: I was banned for 24 hours at first then the next day i log on and it was permanent.

![cynagen](https://user-images.githubusercontent.com/54691727/63983964-f57f6380-ca7d-11e9-9798-9ff659ff632a.png)

**Comment by Kyrobi** [comment]
Brief yourself up with the rules next time.

https://site.cynagen.xyz/rules

**Comment by Kyrobi** [comment]
You were being being troublesome in chat. Since this is your first ban, you'll be given a second change. However, you will be muted for 5 days.
