### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by Dainechan** [Kyrobi/Cynagen#6]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: mazzgamee

**I was banned on**: 4/9/2019

**I was banned by**: Server

**I was banned for**: KillAura

**A brief summary of what happened before the ban was**: I was trying to build a structure underwater, and I kept dying because I thought I would be able to place another block and make it to the surface, but did not rip.

**I like to be unbanned because**: This is a really fun server, and I love building and hanging around with my friends please let me back ><

**I often slap little kids because**: ...

**Additional information**: pls unban ><

**Comment by Kyrobi** [comment]
The entire reason I unbanned you was because I thought the KA was a False positive, it turns out that you admitted to using KillAura. Remember, building a structure underwater does not excuse you from randomly using aura.

Consider this your last warning. You are unbanned.

**Comment by Mickymoo9** [comment]
Hey can i get unbanned I didnt know i couldnt say nigga. I very sorry can i Pls get unban i luv the server.

**Comment by Kyrobi** [comment]
Please make your own issue. Also, this issue is already marked closed
