### ISSUE TITLE
Ban Appeal: Ivan Pavlovich 

### ISSUE THREAD

**Issue by Co8alt** [Kyrobi/Cynagen#60]
My Minecraft Username is Co8alt_
I was banned on the 29th august 8 2019.
I was banned because i said the n word accidentally :(
Before i was banned i was playing survival with my friend and i had a ton of items like wheat,diamonds other resources,building my house,farm etc
I would like to get unbanned ill promise i wont say the n word or anything else that is offensive to other people or be rude to other people and if i get banned again somehow ill accept my ban and i wont write a ban appeal :).
I like to slap kids because they didnt watch Jojo.
I live in Russia,City Vladimir,i mostly starve but its ok i have my budget soo its ok i have no friends i have bad internet :( and i get bullied because i ask people when is Carson streaming.

**Comment by Kyrobi** [comment]
You are unbanned. Please brief yourself over the server rules at https://site.cynagen.xyz.rules
