### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by ThePilot1999** [Kyrobi/Cynagen#61]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: ThePilot1999

**I was banned on**: 09/03/19

**I was banned by**: (Leave blank if unknown)

**I was banned for**: saying the n word

**A brief summary of what happened before the ban was**: I was talking about the movie Blazing Saddles and said "If you take a shot everytime they say (n word) you'd be trashed in first 30 minutes

**I like to be unbanned because**: I should have censored what i said and wont do it again

**I often slap little kids because**: Their tiny faces are perfect for slapping and little kids are annoying

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Pick your poison: 5 days mute or 2-day ban?

**Comment by ThePilot1999** [comment]
I guess I'll do the mute. lol
Guessing i cant just let the 30 minute ban expire?
