### ISSUE TITLE
Ban Appeal: jakearator

### ISSUE THREAD

**Issue by jakearator** [Kyrobi/Cynagen#62]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: jakearator

**I was banned on**: (date) 9/5/2019

**I was banned by**: (Leave blank if unknown) The system. Those damn robots.

**I was banned for**: Saying: "Nigg-"

**A brief summary of what happened before the ban was**: A brief summary on what happened was Bethe and I where messin around in chat like usually, and I said, "Yo, give me the n-word pass" and he said, "If you beat me in a duel, i'll give you it." So, I of course said, "B E T !" When he was building our epic battle scene that was gonna look exactly like Naruto & Sasuke battling I sneaked up behind him and slaughtered him, without hesitating because i'm a sneaky assassin. With him being dead, he typed (I think using /me), "gives jakearator the n-word pass." Right after he did that, I of course, typed in chat, "Nigg-" and never fully said it and instantly got banned. 

**I like to be unbanned because**: I overall enjoy everyone on the server and would terribly miss peeps. I understand that I shouldn't even joke around with saying stuff like this and I understand that, and I wouldn't have done this if I knew this was the punishment regarding using slurs. (I would like to state really quickly too. I am not at all racist, i'm the least from it.. I grew up in Iowa.. plenty of gangs..etc you know what i'm getting at).

**I often slap little kids because**: Man.. FUCK THEM KIDS BRO.. (Blue face baby.. ya ya.. IGHT)
 
**Additional information**: (Optional)
I've recently watched this Step-mom porn and it was really good. He came out of no where when she was cleaning her bed room and said, "Let's do sex" and she said, "We can't do this sex thing anymore" and he said he was Naruto from the fancy anime Naruto Shippuden. After saying that, the girl couldn't do anything. SHE WAS R E A D Y.

![oh ya baby swag](https://user-images.githubusercontent.com/54967605/64394847-0142cb00-d026-11e9-8aa8-0ae97058504b.jpg)

![cat screaming lol](https://user-images.githubusercontent.com/54967605/64394859-0ef85080-d026-11e9-95a1-963d127b4758.jpg)

**Comment by cottoncandyowo** [comment]
It got decided to unban you but just give you the 24 hour mute instead, yeah yeah a i g h t.
![Screen Shot 2019-09-05 at 7 11 45 PM](https://user-images.githubusercontent.com/49377493/64396053-414b8300-d011-11e9-9b63-9e8e60412502.png)
