### ISSUE TITLE
Ban Appeal: GrinchyMC

### ISSUE THREAD

**Issue by GrinchyMC** [Kyrobi/Cynagen#63]
**GrinchyMC**:

**I was banned on 09/06/2019

**I was banned by**: (?)

**I was banned for Xray

**A brief summary of what happened before the ban was I wanted some diamond armor**:

**I like to be unbanned because I really enjoy playing on this server because I play with all my friends on the server and now since im banned I cant really play with them anymore ): **:

**Comment by Kyrobi** [comment]
That's unfortunate. Your ban way stay. This isn't your second time getting banned. Considering that after being banned for the first time and STILL not reading the rules / following them, you will stay banned.

**Comment by Kyrobi** [comment]
That's unfortunate. Your ban will stay. This isn't your second time getting banned. Considering that after being banned for the first time and STILL not reading the rules / following them, you will stay banned.

**Comment by Kyrobi** [comment]
That's unfortunate. Your ban will stay. You were banned before and STILL did not follow the rules.
