### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by will76123** [Kyrobi/Cynagen#66]
"Ban Appeal:" a foolish guy called 'will76123' 

will76123

Saturday 14 September 

I was banned by the console

I was banned for a hacked client

I was using the public enderman farm and i think my kill aura was left on from my survival world. I forgot to load my Minecraft again in normal 1.14 Minecraft and left on the hacked client as im stupid.

I like to be unbanned because I made a silly mistake and love this server and don't want to be banned. It was only about an hour ago but I am already missing the server and the cool community on there.

Don't know why this is on here but here it goes - I often slap little kids because, as my friend chittyrim (as him to confirm if you don't believe me) my form tutor always tells me to slap the year 7s 

No additional information other than please have mercy on me as I made a mistake that I won't do again

Thank you for taking your time to read this and i look forward to playing on the server again.

Yours scenically will

**Comment by Kyrobi** [comment]
You need to be careful. This is your second ban. If you get banned again, there won't be any appeals.

Your permanent ban has been reduced to a 3 day ban.
