### ISSUE TITLE
Ban Appeal: Barrelsrider

### ISSUE THREAD

**Issue by barrelsrider** [Kyrobi/Cynagen#68]
**Minecraft username**: Barrelsrider

**I was banned on**: 19/09/2019

**I was banned by**: (Leave blank if unknown) Server

**I was banned for**: Hacks

**A brief summary of what happened before the ban was**: I was working on my squid farm and was swimming inside waterlogged signs, the server was always teleporting me to the bottom of the water column to the pointwhere I was ban

**I like to be unbanned because**: That is a server bug, I can testify and prove it to you, the bug is probably redoable

**Additional information**: (Optional) You may want to test that for yourself and try to fix it at some point, it may ban people by mistake

**Comment by Kyrobi** [comment]
Unbanned.
