### ISSUE TITLE
Ban Appeal: iTkDonations

### ISSUE THREAD

**Issue by AnotherCreator** [Kyrobi/Cynagen#70]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: iTkDonations

**I was banned on**: 10/12/2019

**I was banned by**: Console

**I was banned for**: "Hacking"

**A brief summary of what happened before the ban was**: I was experimenting with a mechanic that involves a boat and a mine cart. If done correctly, it removes the need for powered rails as the boat assumes total control and allows free movement (https://www.reddit.com/r/Minecraft/comments/cfx9k3/did_you_know_you_can_have_a_boat_in_a_minecart/).

I believe there was a false-positive for speed hacking due to how I was standing on the boat/mine cart while it was moving.

**I like to be unbanned because**: False positive 

**I often slap little kids because**: N/A

**Additional information**: My friend, Kami, who was also banned due to the false positive, is also being affected by this as well.

**Comment by ColtCrohnie** [comment]
You've been unbanned, sorry for the inconvenience
