### ISSUE TITLE
Ban Appeal: Mr_Pants_

### ISSUE THREAD

**Issue by dev-ens** [Kyrobi/Cynagen#71]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
Mr_Pants_
**I was banned on**: (date)
10/25/19
**I was banned by**: (Leave blank if unknown)
server
**I was banned for**:
"hacking"
**A brief summary of what happened before the ban was**:
I was in the end and a shulker was making me float up into a block and glitch around. the server banned me. the same thing happened to two of my friends.
**I like to be unbanned because**:
i did nothing wrong and its a really chill server
**I often slap little kids because**:
:/
**Additional information**: (Optional)
*slides you $20*

**Comment by dev-ens** [comment]
the two others are deathbones044 and Lothlorianelf

**Comment by Kyrobi** [comment]
Confirmed that it was a false ban. You are not unbanned.

**Comment by dev-ens** [comment]
thanks!
