### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by ImporiaGaming** [Kyrobi/Cynagen#72]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
L8rM8
**I was banned on**: (date)
2019/10/26
**I was banned by**: (Leave blank if unknown)
Kyrobi
**I was banned for**:
it just says "Hacking"
**A brief summary of what happened before the ban was**:
I was just afk and I looked at my screen and saw i was banned
**I like to be unbanned because**:
I was falsely banned
**I often slap little kids because**:
I don't slap kids.
**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Hello, after analyzing your screen sharing session, I'm hesitant to unban you.

Here are my concerns:
1). You have a X-ray resource pack. Whether you used it or not is irrelevant right now. For the period of time that I was watching you, there was one instance where you mine some stone behind a lava pool, went down, and found diamonds.  

![download](https://user-images.githubusercontent.com/20980266/67627822-3949db80-f829-11e9-9230-cae6a1f19b95.png)

2). You have the Wurst hacked client installed on your computer. In the screen sharing session, it shows you have it for 1.8. However, in your versions folder, there's two Wurst folder called `wurst` and `Wurst MC 1.8`

3). Impossible block placing action. You placed blocks without even having to look at it. Here: https://www.youtube.com/watch?v=IThzXCTPBXA&feature=youtu.be

Number 3 is what I care about the most. Please explain what you believe happened.

**Comment by Kyrobi** [comment]
Confirmed you were not hacking.
