### ISSUE TITLE
Ban Appeal: For Brannmuffin890

### ISSUE THREAD

**Issue by Brannmuffin890** [Kyrobi/Cynagen#73]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Brannmuffin890

**I was banned on**: (date) 11/17/2019

**I was banned by**: (Leave blank if unknown)

**I was banned for**: X-ray

**A brief summary of what happened before the ban was**: I was mining using x-ray

**I like to be unbanned because**: I didn't know it was against the rules, I had not yet looked at the rules for the server but I have now. I am sorry and I won't do it again

**I often slap little kids because**: I am a bad, stinky boy who used hacks

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Hello, you're permanent ban has been reduced to a 3 day ban.

Please brief yourself on the rules while you wait: http://site.cynagen.xyz/rules/
