### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by xVigilance** [Kyrobi/Cynagen#74]
Minecraft username:
Blu2thYT
I was banned on: (date)
Nov 17th, 2019
I was banned by: (Leave blank if unknown)

I was banned for:
Cheating
A brief summary of what happened before the ban was:
I went into the nether and back into the overworld. Was instantly banned after that. I have shaders on so idk if that counts.
I like to be unbanned because:
I didn't do anything wrong.
I often slap little kids because:
It's fun?
Additional information: (Optional)

**Comment by Kyrobi** [comment]
Hello, modifications to the game such as cheststealer (hacks) and inventory shorting mods are not allowed. 

You have been unbanned.
