### ISSUE TITLE
Ban Appeal: cynicalesbian

### ISSUE THREAD

**Issue by cynicalesbian** [Kyrobi/Cynagen#75]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: cynicalesbian

**I was banned on**: Nov 25 2019

**I was banned by**: (Leave blank if unknown)

**I was banned for**: Hacking

**A brief summary of what happened before the ban was**: I was about to explore a jungle temple with a friend 

**I like to be unbanned because**: I don't think I did anything? Maybe the server sensed an issue with my wifi connectivity.

**I often slap little kids because**: they steal my food

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
You are unbanned
