### ISSUE TITLE
Ban Appeal:  lykos_utulo

### ISSUE THREAD

**Issue by lykos-glitch** [Kyrobi/Cynagen#76]
**Minecraft username**: lykos_utulo

**I was banned on**: 25/11/2019

**I was banned by**:  Succubi_Snow

**I was banned for**: Fly-hacks and failing

**A brief summary of what happened before the ban was**: I was playing the game as if normal,  all i was doing was trying to tame this skeleton horse i found

**I like to be unbanned because**: I don't think i was hacking, I certainly wasn't flying. There were a few issues with my internet and connectivity that night but i don't know if that could've been it
I really just like playing on this server

**I often slap little kids because**: they take my legos

**Additional information**: (im too broke for legos)

**Comment by Kyrobi** [comment]
Confirmed it was a false ban. Unbanned
