### ISSUE TITLE
Bug: Bows not working in EternalWinters nether.

### ISSUE THREAD

**Issue by FJTAM** [Kyrobi/Cynagen#77]
Please title this post: "Bug:" followed by a name.

**Minecraft username**: FJTAM

**Expected behavior**: Bows draw back and shoot

**Actual behavior**: bows are stuck in the drawing animation and do not fire

**How can this issue be replicated?** draw a bow in eternalwinter nether

**A screenshot / video link if available**:

**Additional information**: same thing happened in main server end

**Comment by Kyrobi** [comment]
Intentional
