### ISSUE TITLE
Player Report: Mr_Swindle

### ISSUE THREAD

**Issue by nintendose** [Kyrobi/Cynagen#8]
**My Minecraft username**: nintendose

**I am reporting**: Mr_Swindle

**I'm reporting this person for**: being an annoyance, alting to grief in my town, and griefing on his main as well.

**Screenshot or video link if available**: not available

**Additional information**: (Optional) he'd frequently break holes into my barn to get in because he was "lazy to use the main entrance," broke my torches and placed wet sponge everywhere, and when on his alt, he planted jungle saps everywhere and blamed it on raleigh.

**Comment by Kyrobi** [comment]
I have already tome him what is expected of him. Please open another issue or re-open this one if anything else were to occur
