### ISSUE TITLE
Ban Appeal: LittleBlue4201 I was banned on November 26 2019 I was banned for saying the word Niggers I was trying to play with my friends and my little brother got on my computer while trying to get my hot cheetos and he said the word nigger Id Like to be unbanned because i want to play minecraft survival with my friends and i cant because im banned and im sorry it wont happen again i wish for you to consider this appeal that would be greatly appreciated.

### ISSUE THREAD

**Issue by blue4201** [Kyrobi/Cynagen#80]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (date)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**I often slap little kids because**:

**Additional information**: (Optional)

**Comment by Aericio** [comment]
buddy lol `title !== description`

**Comment by Kyrobi** [comment]
This is the 3rd issue this dude has opened and failed. 

Ah yes, every time someone says the n word, it's always the sibling.
