### ISSUE TITLE
me did the oopsie can i be unbanned

### ISSUE THREAD

**Issue by woffiluwu** [Kyrobi/Cynagen#83]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username*woffil*:

**I was banned on**: (date)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was*I was bored so I was xraying (this is so sad)*:

**I like to be unbanned because*I promise I aint gonna do it again*:

**I often slap little kids because*they thicc*:

**Additional information*pls gamer unban I wont do it again the community is pretty gamer uwu,*: (Optional)

**Comment by woffiluwu** [comment]
p l e a s e I e s ;n'

**Comment by Kyrobi** [comment]
"I was bored so I was xraying," well that's unfortunate.

**Comment by woffiluwu** [comment]
Ya but like. I wanna be unban me already said I was soz spongeboy me bob  Sent from Mail for Windows 10 From: KyrobiSent: Wednesday, December 11, 2019 10:38 AMTo: Kyrobi/CynagenCc: woffiluwu; AuthorSubject: Re: [Kyrobi/Cynagen] me did the oopsie can i be unbanned (#83) Closed #83.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kyrobi** [comment]
No. There's like not a single ounces in your initial post, and you gave a terrible reason to Xray.
