### ISSUE TITLE
blitzbite5 I was banned on 2019-11-18, I was banned by Kyrobi, I was banned for supposedly hacking, I don't even know what type of hacking (beacause I didn't do any hacking) they were banning me for, i don't even know if i was logged in at the time,  I like to be unbanned because i did not do any hacking nor did i use any xray or any texture pack for that matter, I often slap little kids beacause, they are pathetic.

### ISSUE THREAD

**Issue by Blitzbite5** [Kyrobi/Cynagen#85]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:

**I was banned on**: (date)

**I was banned by**: (Leave blank if unknown)

**I was banned for**:

**A brief summary of what happened before the ban was**:

**I like to be unbanned because**:

**I often slap little kids because**:

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
You're unbanned.
