### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Aasgaard5** [Kyrobi/Cynagen#86]
I, Aasgaard5, was banned on 2019-12-25 by the server for 'hacking.' I am unsure as to what hacking is being referred to, since I was only running to the enderman farm. I would like to be unbanned since I was indeed not hacking and enjoy playing on the server. I often slap little kids because I strongly dislike them

**Comment by Kyrobi** [comment]
Confirmed that it was a false banned. You are unbanned.
