### ISSUE TITLE
I have questions

### ISSUE THREAD

**Issue by Mikkelator2000** [Kyrobi/Cynagen#88]
I joined the server yesterday, but today it looks like i have been banned? I haven't done anything against the rules and i dont understand why this happened. 
I would like an explanation. My username is Mikkelator2000 on MC and Memetic Kill Agent on Discord. 
If i could have a talk with anyone of the staff that would be great. 

Speak to you soon, Me

**Comment by ColtCrohnie** [comment]
When you try to join the server what does the ban reason say? Would you be able to fill out a ban appeal?
