### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by willcherrington71623** [Kyrobi/Cynagen#89]
I don't know if this is the right place but I went to the suggestions tab on the Cynagen website and it lead me here.

Anyway, my suggestion is that could we have a vote on the rewards for the voting system. I think people would prefer to have more money and to buy diamonds rather than be given then, same possibly for wood and food. I assume the food is possibly there for new players, but instead, we could have a kit starter with some wood and food as a one-time use kit or something that could be used every 24hrs or something.

Thanks for reading.

**Comment by Kyrobi** [comment]
It's relatively balanced for both new and old players.
