### ISSUE TITLE
Bug: Elytra lagging back

### ISSUE THREAD

**Issue by JokerBoss99** [Kyrobi/Cynagen#9]
**Minecraft username**: JokerBoss99

* Expected behavior**: Be able to fly long distances in any world without getting lagged back by anticheat

**Actual behavior**: Get lagged back after a long distance has been flown without touching the ground.

**How can this issue be replicated?** Fly in the nether with an elytra, and just don't stop using rockets. You will be lagged back

* A screenshot / video link if available**: N/A Will edit if I record it

**Additional information**: Nope

**Comment by Kyrobi** [comment]
Does this only work in the nether, or does this happen in the overworld too?

**Comment by Kyrobi** [comment]
Can confirm this is an issue. Will be fixing
