### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by BluHardt** [Kyrobi/Cynagen#92]
Ban Appeal: Black_Toby 

**Minecraft username**: Black Toby 

**I was banned on**: 06/01/20

**I was banned by**:

**I was banned for**: Apparently "being a troll", I was joking and thought others were in on the joke, but apparently someone got offended and banned me. I dont feel its fair to perma ban someone without warning first. 

**A brief summary of what happened before the ban was**: As a black person i regularly use the n-word (as my right), i made a joke saying "N!ger" clearly using an exclamation mark in place of an I. of course this is against server rules and i apologise. I feel i could have atleast been given a suspension first. Following the "incident", multiple members or the server joined in on the joke, many stating how its "not offensive", or "hes black he can say it if he wants". 

**I like to be unbanned because**: I feel that this was an unfair action made against me, without first giving me the opportunity to rectify my mistake. I would like to be unbanned, as i enjoy playing on the server, especially as I have friends that use the server regularly.

**I often slap little kids because**: I dont slap little kids 

**Additional information**: I am sorry for going against server rules, and if given the opportunity i will become a decent member of the server and no longer a "troll" as i was labelled. 

Kind Regards, 

Black-Toby

**Comment by 0x1c1ean** [comment]
Typing the word nigger or niger in the chat automatically bans you for 2 days, not permaban.

**Comment by Kyrobi** [comment]
Fortunately, your rights do not supersede the server's rules.

You seem to understand your mistake and willing to learn. As a fair punishment, you'll receive a 12-hour mute.

Please use this time to brief yourself up on the rules. There are only 6 rules. However, this page goes into heavy details on what each of the rules mean: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md
