### ISSUE TITLE
Ban Appeal: Skullyboi10

### ISSUE THREAD

**Issue by skullyboi10** [Kyrobi/Cynagen#93]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Skullyboi10

**I was banned on**: 12/19/2019

**I was banned by**: succubi snow

**I was banned for**: griefing

**A brief summary of what happened before the ban was**: I really don't know why I was banned for griefing, my friends were banned for the same reason but we never griefed anyone.
I recently complained and used profanity on the discord, which I apologize for. I thought I was going to be banned for good and was pretty salty about losing my work
**I like to be unbanned because**: I've made a few acquaintances on the server and would like to keep them, I also have put a decent amount of effort into my base and would not like to lose it.

**I often slap little kids because**: Those little shits deserve it

**Additional information**: (Optional)

**Comment by skullyboi10** [comment]
Revision on the date it was 12/28/2019

**Comment by Kyrobi** [comment]
Resolved.
