### ISSUE TITLE
Ban Appeal: Fargale

### ISSUE THREAD

**Issue by Fargale** [Kyrobi/Cynagen#94]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Fargale

**I was banned on**: (date) 8/01/2020

**I was banned by**: (Leave blank if unknown) Server

**I was banned for**: Slurs

**A brief summary of what happened before the ban was**: I misspelled my name, a VERY easy mistake to make

**I like to be unbanned because**: It's a simple misspelling, I clearly didn't mean to use it as a slur, it's my name.

**I often slap little kids because**: They deserve it

**Additional information**: (Optional) Perhaps lax the restrictions a bit? It's a fairly common mistake to make, and while this is the first time it's happened for me, I have a sense of impending doom

**Comment by Kyrobi** [comment]
Resolved
