### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by tiqss** [Kyrobi/Cynagen#95]
To Whom it may concern,
This is about my permanent ban on cynagen.xyz (good server!) under the account name of tiqss, I was banned for x-ray yes I admit to x-ray I did use it but one of the main reasons I did was because I made my friend rage quit and leave the discord call I was in with him because I had setup a trap in his house while he was afk, I felt really bad and wanted to make up for him by getting him a few diamonds, I know this isn't the most valid point but I really enjoyed playing on the server and would like to get back to it. you don't have to unban me immediately but I would really appreciate a temporary ban instead of a permanent ban, yes I know I cheated but I truly enjoy playing on cyagen.
![image](https://user-images.githubusercontent.com/59627857/71936338-3f7f0f80-31fd-11ea-870b-6959d7ac165e.png)

From Tiqss.

**Comment by ColtCrohnie** [comment]
Please use the proper Ban Appeal Template available, afterwards you’re appeal will be reviewed
