### ISSUE TITLE
Ban Appeal: ItsBenDavis

### ISSUE THREAD

**Issue by ItsBenDavis** [Kyrobi/Cynagen#96]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
ItsBenDavis
**I was banned on**: (date)
1/7/19
**I was banned by**: (Leave blank if unknown)

**I was banned for**:
Cussing
**A brief summary of what happened before the ban was**:
I said the n word I’m black I can say it if I want and some dude named something that started with an e was cussing me out and I said the n word
**I like to be unbanned because**:
The server is cool
**I often slap little kids because**:
Excuse me?
**Additional information**: (Optional)
N/A

**Comment by Kyrobi** [comment]
I can leave you banned if I want.

**Comment by ItsBenDavis** [comment]
Geez y’all are rude

**Comment by VulcanGamersHD** [comment]
No nword shall be spoken regardless of your race. Next time make yourself sound more sincere in your appeal.

**Comment by ItsBenDavis** [comment]
Y’all are racist you SOBs you whiney little shits

**Comment by JokerBoss99** [comment]
I would think that directing racist language (what you did) is racist, and getting rid of that language is better than having it but you do you man! Go be a racist!

**Comment by Kyrobi** [comment]
I love being a racist; it makes me happy

**Comment by VulcanGamersHD** [comment]
"whiney little shits" who tf is the one whineying about not being about to be racist?

**Comment by ItsBenDavis** [comment]
That made no sense

**Comment by Kyrobi** [comment]
I'm locking this thread as it's going nowhere.
